assets/schema/ensemble_schema.json, lib/widget/form_checkbox.dart, lib/widget/form_date.dart, lib/widget/form_helper.dart, test/widget/checkbox_switch_test.dart
- DateInput, Checkbox and Switch now properly use the global styles.
- DateInput can hide its calendar icon
- Checkbox / Switch text now properly wrap.
- Add Checkbox/Switch widget tests.
=> Fix DateInput, Checkbox, Switch alignment/styling issues

lib/framework/data_context.dart, lib/screen_controller.dart, lib/util/upload_utils.dart
Ticket: #243 
For flutter web, instead of using `file.path` we can use `file.bytes`. [reference](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ)
=> File upload for flutter web

ensemble/integration_tests/default/API Bindings.yaml, ensemble/integration_tests/default/Widget Bindings.yaml, integration_test/defaultapp_test.dart, lib/ensemble_app.dart, lib/framework/scope.dart, lib/framework/view/page.dart, lib/framework/widget/widget.dart, pubspec.yaml, test/invokable_test.dart
Widgets from our YAML is being re-used for optimization. This creates a situation where multiple State objects can be created for the same Widget. This is normally OK, except we try to remove the binding listeners when a widget state is disposed (which is a problem when the old State is removed, but the widget remains with its other States).
The solution is to only remove all binding listeners when the Page is disposed (e.g. navigating away), since these YAML widgets are always alive as long as the page exists.
Also added integration tests for Binding.
For more information, see https://api.flutter.dev/flutter/widgets/StatefulWidget-class.html. Copied snippet below:
```
The framework calls [createState](https://api.flutter.dev/flutter/widgets/StatefulWidget/createState.html) whenever it …
```
=> #305 Fixed binding listeners being removed when widget state is disposed

assets/schema/ensemble_schema.json, lib/framework/action.dart, lib/screen_controller.dart, lib/util/upload_utils.dart, lib/util/utils.dart
Added new property to uploadFiles fieldName, so users can override default field name in multipart/form-data from 'files' to whatever their servers are expecting.
=> Ability to override field name

lib/framework/widget/error_screen.dart, lib/framework/widget/view_util.dart
Renders error screen as an overlay to avoid render constraints from parent widget when an error is caught during build phase
=> #364 Throw language error for unsupported widget during build phase

lib/ensemble_app.dart, lib/widget/helpers/widgets.dart, lib/widget/input/dropdown.dart
Leverages new SelectionArea utility widget from flutter to enable selection across all screens in Ensemble https://api.flutter.dev/flutter/material/SelectionArea-class.html
=> #368 Make content selectable by default

lib/layout/box/box_utils.dart
Ticket: #427 
Fixed the gap issue in `item-template` of flex widgets
<details>
<summary>Sample YAML Code</summary>
```yaml
View:
styles:
useSafeArea: true
backgroundImage:
source: https://firebasestorage.googleapis.com/v0/b/ensemble-web-studio.appspot.com/o/demo_apps%2Fkitchen-sink%2Fbeach_sunset.jpg?alt=media&token=a197bdb1-7b8f-479a-9fee-722ec7857c97
onLoad:
invokeAPI:
name: getHotels
Column:
styles:
padding: 15 24
gap: 36
children:
- Column:
styles:
padding: 15 24
gap: 8
children:
- Button:
label: Log In
- Button:
label: Sign In
- Button:
label: Logout
- Column:
styles:
padding: 15 24
gap: 30
item-template:
data: ${getHotels.body.hotels}
name: hotel
template:
Button:
label: ${hotel.name}
API:
getHotels:
inputs: [location, from, to]
authorization: none
uri: …
```
=> Fixed gap issue in item-template of flex widgets

lib/ensemble.dart, lib/ensemble_provider.dart, lib/host_cache_provider.dart, lib/page_model.dart, lib/provider.dart
Support widgets defined at the app level, as well as imported apps (currently hardcode to just 8PghcmhtGkWiWffmhDDl)
At runtime we'll fetch artifact 'resources', which has the following signature:
```
Widgets:
customWidget1:
inputs: ..
body: ...
anotherCustomWidget:
body: ...
// for later  
Code:
API:
```
We then iterate through each imported apps (current just 1 app 8PghcmhtGkWiWffmhDDl) and add the custom widgets with namespace to the resources)
=> Add support for custom widgets from Runtime

lib/widget/carousel.dart
Ticket: #465
In this PR, I fixed the padding issue and also removed the default padding for the leading and trailing items.
`gap: 10` -> It adds the gap between the children. Default value is 10
`leadingGap: 10` -> It adds the gap at the start of the first item. Default value is 0
`trailingGap: 10` -> It adds the gap at the end of the last item. Default value is 0
=> Fixed carousel padding issue

lib/widget/button.dart
Ticket: [#450](https://github.com/EnsembleUI/ensemble/issues/450)
In this PR, I fixed some Button Issues
1. Gradient is not filled for the entire button. It applied only to the BoxWrapper
2. onTap is not called in the padding area of the button
3. Outline button has an extra border by default. It will display two borders on the button
Issue Video:
Sample YAML:
```yaml
View:
title: Home
body:
Column:
styles:
crossAxis: center
children:
- Button:
styles:
backgroundColor: blue
backgroundGradient:
colors:
- amber
- blue
start: bottomRight
end: topLeft
padding: 20 60
margin: 10 10
fontSize: 20
label: Filled
onTap: |
//@code
console.log("filled button tapped");
- Button:
styles:
outline: true
color: green
borderColor: red
borderRadius: 5
borderWidth: 3
padding: 20 20
margin: 30 10
fontSize: 20 …
```
=> Fixed button padding, gradient and onTap issue

assets/schema/ensemble_schema.json, lib/layout/data_grid.dart
Fixes: #494 #512 
In this PR, I changed the border styling of grid view it's because of an issue in the borderRadius of TableBorder default constructor. Now it's changed it `TableBorder.all` named constructors with `color`, `width` and `borderRadius` only.
**Sample YAML**
```yaml
DataGrid:
border:
borderRadius: 30
color: red
width: 4
```
=> Changed border styling of data grid view

lib/framework/view/bottom_nav_page_group.dart
Ticket: #552 
In this PR, I added notch color, height, and padding styles for the bottom nav bar.
If notch color is null it uses Theme.of(context).scaffoldBackgroundColor by default.
**BottomNavBar Styles**
```
BottomNavBar:
styles: { 
backgroundColor: indigo, 
color: green, 
selectedColor: blue, 
floatingBackgroundColor: blue, 
floatingIconColor: white, 
notchColor: black,
height: 60,
padding: 0 20,
}
}
```
=> Added few more style properties to Bottom Navigation Bar

lib/widget/input/dropdown.dart, lib/widget/input/form_textfield.dart
Ticket: #624 
In this PR, I added focus and unfocus functionality for the text input field. You can invoke the keyboard action (focus & unfocus) like below
```
textInputFieldId.focus();
textInputFieldId.unfocus();
```
=> Add text input field focus and unfocus

assets/schema/ensemble_schema.json, lib/util/input_formatter.dart, lib/widget/input/form_textfield.dart, pubspec.yaml
Ticket: #629 
**Sample EDL**
`#` match to the number and `A` to the letter
```yaml
View:
header:
title: MaskTextInput
styles:
body:
Column:
styles:
gap: 16
padding: 30
children:
- TextInput:
label: Example 1
hintText: "Ex: +2 (312) 234-56-89"
mask: "+# (###) ###-##-##"
inputType: number
required: true
- TextInput:
label: Example 2
hintText: "Ex: 11/12/2020"
mask: "##/##/####"
inputType: text
required: true
- TextInput:
label: Example 3
hintText: "Ex: 1234.SBCWEF/25AB"
mask: "####.AAAAAA/##AA"
inputType: text
required: true
```
=> Add text field input mask

lib/ensemble.dart, lib/ensemble_app.dart
I need the ability to run a code block exactly once, even if this code block is inside a widget that can be rebuilt at anytime. Reasons are uniquely to us:
1. don't want to put it inside main(). Customers should be able to simply use EnsembleApp as a widget with zero other setup.
2. Root-level widget EnsembleApp can be rebuilt multiple times - since EnsembleLive relies on a brand new EnsembleApp() with unique key every time for cache busting. Plus customers can recreate this widget any time.
=> Ensure the singleton managers' initialization is run at most once

assets/schema/ensemble_schema.json, lib/framework/action.dart, lib/framework/permissions_manager.dart, lib/screen_controller.dart, pubspec.yaml
Note that we use 2 packages for notification: flutter_local_notifications and firebase_messaging. The former is not capable to checking permission reliably across platforms, while the latter has not been officially merged in by @snehmehta . Hence here i'm directly import firebase_messaging. Both of these libraries should be moved to its own module.
=> add checkPermission action for checking notification status

lib/util/upload_utils.dart
Issue:
Flutter web camera files has path of blob which aren't supported by `uploadFiles` actions so this PR updates includes prioritising adding multipart using bytes to the request which fixes the issue.
Context:
https://discord.com/channels/1031982848485359626/1088664937288699992/threads/1141754319893442643
=> fixed flutter web camera file upload

assets/schema/ensemble_schema.json, lib/framework/action.dart, lib/framework/device.dart, lib/screen_controller.dart, pubspec.yaml
Ticket: #709 
In this PR, I added the functionality for opening the app settings. You can do it in two ways
1. Invoke it using `openAppSettings` ensemble action with the target
2. Using `device.openAppSettings()` with target from Javascript
**Both platforms supported targets**
1. settings
2. notification
**iOS supported targets**
1. subscriptions
**Android supported targets**
1. accessibility
2. alarm
4. apn
5. batteryOptimization
6. bluetooth
7. dataRoaming
8. date
9. developer
10. device
11. display
12. hotspot
13. internalStorage
14. location
15. lockAndPassword
16. nfc
17. security
18. sound
19. vpn
20. wifi
21. wireless
YAML
```yaml
View:
header:
title: App Settings
styles:
scrollableView: false
body:
Column:
styles:
gap: 24
padding: 24
mainAxis: start
crossAxis: center
children:
- …
```
=> Open App settings

lib/framework/data_context.dart
Ticket: #746
From **Ensemble**
```yaml
Button:
label: SaveToKeychain
onTap:
executeCode:
body: |
//@code
ensemble.saveToKeychain("flutter", {"name": "Vinoth"})
console.log("saveToKeychain called");
```
In **AppDelegate.swift**
=> Refactor saveToKeychain method

assets/schema/ensemble_schema.json, lib/widget/confirmation_input.dart, lib/widget/helpers/controllers.dart
In this PR, I added a few properties and methods for the **ConfirmationInput** widget
**Style Properties:**
1. fieldHeight
2. fieldWidth
3. gap
4. borderRadius
5. borderWidth
6. Added custom type for field
NOTE: 4th and 5th properties will work only if you've `fieldType` as `custom`
**Methods:**
1. clear
2. focus
3. unfocus
=> Add clear, focus and unfocus methods and few more style properties to ConfirmationInput widget

assets/schema/ensemble_schema.json, lib/framework/model.dart, lib/widget/helpers/widgets.dart
Ticket: [#798](https://github.com/EnsembleUI/ensemble/issues/798)
Removed image from the BoxDecoration and added the `backgroundImage` as a image widget inside the stack along with the child widget.
=> Update BoxWrapper to support fallback backgroundImage

assets/schema/ensemble_schema.json
I tested it locally in the IDE and it's working fine. Showing completion for all the menus but in the dev studio ensemble it's not showing the autocomplete. I took ensemble_live build from this branch and tested the web studio, it's not showing the console.
In some places, I'm getting this issue - Matches multiple schemas when only one must validate.yaml-schema: Ensemble(0)
Also another one thing we need to do, we've change the way to write Icon widget right? It's not updated in some of the widgets. We've icon schemas called HasIcon and BaseIcon payload. Both looks like same.
=> fix(schema): update menu schemas

lib/framework/widget/has_children.dart
Previously we created a widget outside, then pass it to the parent to add it to the parent tree. This is a problem on rebuild since the widget's context (created outside) is different, which cause the State to rebuild but retain the StatefulWidget. This was missed until we put the code in to remove a widget's binding listeners on dispose(). Since the key to remove the listener is the StatefulWidget, which stays the same while we have multiple States.
With this change, the StatefulWidget and the State are always in lock step. They are still created more often than necessary, but that's another optimization for another day.
=> Defer building the child widgets to the parent's build()

assets/schema/ensemble_schema.json, lib/ensemble.dart, lib/framework/action.dart, lib/framework/menu.dart, lib/framework/view/page.dart, lib/framework/view/page_group.dart, lib/framework/widget/screen.dart, lib/page_model.dart, lib/screen_controller.dart
Ticket: #440 
EDL remains the same i.e pass the screen name.
Only configuration needs to be done on flutter side that is pass custom widgets along with name.
Example:
```dart
void main() async {
WidgetsFlutterBinding.ensureInitialized();
// (optional) pre-initialize asynchronously so Ensemble is ready
// when your app switches to Ensemble screens. Add `await` before
// this statement if your first page is an Ensemble's page.
Ensemble().initialize();
/// (optional) set map of custom flutter widget that can be called from ensemble
Ensemble().setCustomFlutterWidgets(
{
'testScreen': (context, args) =>
TestScreen(name: args?['name'] ?? 'Hello'),
},
);
runApp(const MyApp());
}
```
EDL to navigate to `TestScreen` will be no different, 
```yaml
- Button:
label: Test Screen
onTap: …
```
=> Navigate to flutter screen

assets/schema/ensemble_schema.json, lib/framework/view/bottom_nav_page_group.dart
Ticket: [#869](https://github.com/EnsembleUI/ensemble/issues/869)
```yaml
BottomNavBar:
styles:
{
backgroundColor: indigo,
color: green,
selectedColor: blue,
floatingBackgroundColor: blue,
floatingIconColor: white,
notchColor: white,
height: 60,
padding: 0 20,
borderRadius: 30 30 0 0,
}
```
=> Add borderRadius for the bottom nav bar

lib/widget/input/dropdown.dart
This PR includes a fix for the https://github.com/EnsembleUI/ensemble/issues/877 in which there were unnecessary onChanged callbacks happening when the same item was selected in the dropdown which was previously selected.
=> Fixed unnecessary callbacks in dropdown

assets/schema/ensemble_schema.json, lib/framework/action.dart, lib/framework/view/bottom_nav_page_group.dart, lib/framework/view/page_group.dart, lib/widget/image.dart
```yaml
Button:
label: Navigate To Cast
onTap:
navigateViewGroup:
viewIndex: 2
```
Video:
https://drive.google.com/file/d/1HLBquNs0E1fHlIjyNnKDNFhegcma2V35/view?usp=share_link
=> Add navigate to view group action

lib/framework/action.dart, lib/framework/view/bottom_nav_page_group.dart, lib/framework/view/page_group.dart
Ticket: #855
Now it supports all the menu and the reloadView works correctly with these changes
- Drawer
- SideBar
- BottomNavBar
```yaml
Button:
label: Navigate To Chat
onTap:
navigateViewGroup:
viewIndex: 2
```
Video:
https://drive.google.com/file/d/1btA1-lZ53Opkx5ddRxhdF7ZP2PYbrvvE/view?usp=share_link
=> Add navigate to view group action - v2

assets/schema/ensemble_schema.json, lib/layout/list_view.dart, lib/page_model.dart
closes: Loading for infinite scroll View #920
+1 Enhance:
Now we can by pass the ensemble storage and directly concat data to `[id].data`.
Sample YAML
```yaml
ListView:
id: listView
styles: { reverse: true }
loadingWidget:
Progress:
display: linear
styles:
color: blue
onScrollEnd:
invokeAPI:
name: getPeople
onResponse: |
//@code
var results = getPeople.body.results;
listView.data = listView.data.concat(results);
listView.showLoading = false;
item-template:
data: ${getPeople.body.results}
name: user
template:
MyRow:
inputs:
p: ${user}
```
=> listView: show loading indicator

lib/ensemble.dart, lib/ensemble_app.dart, lib/ios_deep_link_manager.dart
Ticket: #958
In this PR, I added an `addCallbackAfterInitialization` and `getCallbacksAfterInitialization`. Also updated the ensemble app to execute all the registered functions
=> Add callbackAfterInit methods for executing functions after the app is initialized

lib/ensemble.dart, lib/ensemble_app.dart, lib/ios_deep_link_manager.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/958
Enhancement:
In this PR, I entirely refactored the method calling after an ensemble app initialized.
1. `addCallbackAfterInitialization` - It stores the method in the `_afterInitMethods` (List of type Function)
2. `getCallbacksAfterInitialization` - It returns `_afterInitMethods` (List of type Function)
3. When the ensemble app is initialized or resumed, it executes the `executeCallbacks` method which will remove a method which is stored in the `getCallbacksAfterInitialization` and execute that removed method.
4. Error handled
=> Simplified callbackAfterInit method call logic and handle errors

assets/schema/ensemble_schema.json, lib/widget/carousel.dart, lib/widget/image.dart
In this PR, I've fixed a few issues and updated the schema
**1. Index Updates:** Ticket: #949 and #955
1. `currentIndex`
- For setting the initial index of the carousel which starts the carousel from that child of index.
- To get the current index which is displayed in the carousel
- Default (0)
2. `selectedIndex` 
- To get the selectedIndex only when the user clicks on the carousel item otherwise it'll return -1. Default (-1)
3. `indicatorMaxCount` 
- This property shows a limited number (for ex: 4) of **carousel indicator** when creating the carousel with more (for ex: 100+) items. 
- Default (null), if this property is null the indicator works normally how it works before (based on the currentIndex property)
**2. Indicator Alignment and Padding** - Ticket: …
=> Added currentIndex, selectedIndex and indicatorMaxCount properties for Carousel Widget

assets/schema/ensemble_schema.json, lib/action/upload_files_action.dart, lib/framework/action.dart, lib/screen_controller.dart, lib/util/utils.dart
closes: https://github.com/EnsembleUI/ensemble/issues/975
Introducing `batchSize` option in `uploadFiles`, we can specify number of batch of files to be uploaded with a single http call.
Sample EDL
```yaml
Button:
label: Upload Picked files
onTap:
pickFiles:
id: picker
allowMultiple: true
onComplete:
uploadFiles:
id: fileUploader
files: ${picker.files}
uploadApi: fileUploadApi
options:
batchSize: 2
onComplete: |
//@code
console.log(fileUploader.body);
onError: |
//@code
console.log('Failed');
```
=> uploadFiles: new option batchSize

assets/schema/ensemble_schema.json, lib/widget/carousel.dart
This `selectedIndex` property is changed only from the framework when the user taps any of the carousel item. So it should not be exposed to the user. Just removed it.
=> Remove selectedIndex from the setters method

lib/widget/input/form_textfield.dart
Ticket - https://github.com/EnsembleUI/ensemble/issues/1017
In this PR, I added the following
1. Added a toolbar with done button for the keyboard which has input type of `number` and `phone` of `TextInput`
2. `onTapOutside` method in the TextFormField, which will remove the keyboard focus automatically
=> Add keyboard toolbar with done button

assets/schema/ensemble_schema.json, lib/framework/menu.dart, lib/framework/view/bottom_nav_page_group.dart
In this PR, I added the following
1. Added `onTap` action for all nav bar item
2. Currently, the `onTapHaptic` is added only for the FAB. Now I added it for other items too
3. Added `switchScreen` property, this will disable the page switching and the bottom nav bar item selected states. Developer have to manually invoke whatever the page they want to with the `onTap` action callback
=> Add switchScreen, onTap and onTapHaptic actions for the bottom nav bar item

.github/workflows/trigger-preview-build.yaml
Dispatch event to run studio preview builder workflow in `ensembleUI/ensemble_live` repo when PR is closed on main.
https://github.com/EnsembleUI/ensemble_live/actions/workflows/studio-preview-deploy.yml
=> preview build trigger

lib/widget/calendar.dart, pubspec.yaml
- new methods for calendar mark, unmark, select, unselect cell with start end dates
https://github.com/EnsembleUI/ensemble/issues/1136
```js
calendar.markStartEndCell("2024-01-01", "2024-01-10"); 
```
=> mark cell with start and end date

lib/layout/form.dart, lib/widget/helpers/widgets.dart
- FormInput now properly use its labelStyle.
- When rendering Form inputs, use the Form's labelStyle if can't find a labelStyle at the input level
=> Fix form label styles

lib/ensemble.dart, lib/framework/notification_manager.dart, lib/framework/view/page.dart, lib/framework/widget/screen.dart
Two separate issues:
1.  Depending on the order of execution, some time the Notificaiton's screen appear first then the Home screen comes in.
2.  Screen order is correct, but Back button doesn't work on Notification's screen. The problem was because Landing screen calls an API then redirect the user to Home. When notification comes in in terminated state, it executes the notification's page navigation BEFORE the Landing screen even returns the API.
The fix are both:
1. Make sure notfication's screen executes AFTER Landing Screen's onLoad.
2. Refactored apps logic to not call an API onLoad. This actually fixed a separate issue where a delay is there before the hoem screen loads
=> Fixed notification on terminated state

assets/schema/ensemble_schema.json, lib/widget/switch.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1154
Added the following
1. height
2. width
3. custom - If it's true, we've to manually change the switch from onChange callback using the `event.data.value`
4. Updated the schema
Updates (30 Jan):
- Deleted custom property and it's logic
- Fixed the null issue in the switch widget
```yaml
TripleSwitch:
id: tripleSwitchId
leadingText: "Entire Place"
value: mixed
enabled: true
required: true
width: 150
height: 50
styles:
{
activeThumbColor: white,
inactiveThumbColor: grey,
activeColor: 0xFFD6D6CE,
inactiveColor: 0xFF425C59,
mixedColor: 0xFF858174,
}
onChange:
executeCode:
body: |
//@code
console.log("TripleStateSwitch Value: "+this.value);
```
=> Add height, width properties to switch and update schema

lib/widget/input/form_textfield.dart
Ticket: [#1184](https://github.com/EnsembleUI/ensemble/issues/1184)
It applicable for both TextInput and PasswordInput widgets
Doc - https://github.com/EnsembleUI/ensemble_docs/pull/143
Schema (BaseTextInput) - https://github.com/EnsembleUI/ensemble-web-studio/pull/711
**Sample EDL**
```yaml
PasswordInput:
label: Password
value: EnsembleUI
obscureToggle: true
readOnly: true    # If true, the text input is to be read-only, text cannot be modified
selectable: true     # If true, It will enable features such as long-pressing the TextField to select text and show the cut/copy/paste menu, and tapping to move the text caret text.   
```
=> Add selectable and readOnly property to text input field

lib/layout/tab_bar.dart
Ticket: [#1162](https://github.com/EnsembleUI/ensemble/issues/1162)
Docs: https://github.com/EnsembleUI/ensemble_docs/pull/149
Schema: https://github.com/EnsembleUI/ensemble-web-studio/pull/711
Now by default, it uses the start (without padding)
```yaml
TabBar:
id: tabBarId
styles:
tabAlignment: start | startOffset | fill | center
```
=> Add tabAlignment property to TabBar view

lib/framework/action.dart, lib/framework/view/bottom_nav_page_group.dart, lib/framework/view/page.dart, lib/framework/view/page_group.dart
Closes: https://github.com/EnsembleUI/ensemble/issues/1345
Added support for inputs / payload to `navigateViewGroup` action
```yaml
navigateViewGroup:
viewIndex: 1
inputs:
foo: bar
```
=> inputs / payload support to navigateViewGroup

lib/ensemble_app.dart, lib/framework/action.dart, lib/screen_controller.dart, lib/util/utils.dart
Added new parameter to navigateScreen called `asExternal` this uses externalNavigateKey to push screen. This allows integration of flutter app and ensemble app seems seamless. 
```
Button: 
label: Push screen using external key
onTap:
navigateScreen:
name: Tournaments
asExternal: true
```
=> Push screen using external navigation key

modules/ensemble/lib/action/Log_event_action.dart, modules/ensemble/lib/framework/action.dart, modules/ensemble/lib/framework/data_context.dart, modules/ensemble/lib/framework/logging/console_log_provider.dart, modules/ensemble/lib/framework/logging/log_manager.dart, modules/ensemble/lib/framework/logging/log_provider.dart, modules/ensemble/lib/framework/stub/analytics_provider.dart, modules/firebase_analytics/lib/firebase_analytics.dart
- restructured analytics to make it flexible to support more operations
- added setUserId support
previous EDL:
```yaml
logEvent:
name: "Restaurant_Clicked"
parameters:
restaurant_name: ${name}
restaurant_Id: ${cafeId}
timestamp: ${ensemble.formatter.now().getDateTime()}
```
new EDL:
to log event
```yaml
logEvent:
provider: firebase # default firebase
operation: logEvent # default logEvent
name: "Button_Clicked" # required if operation is logEvent
parameters:
button_name: "Login"
screen_name: "Login Screen"
timestamp: "2024-06-04T12:00:00"
```
to set user id
```yaml
logEvent:
provider: firebase
operation: setUserId
userId: "user123" # required if operation is setUserId
```
with this structure, analytics can be much more powerful
1. We can add more analytics libraries in `provider` 
2. …
=> firebase analytics

modules/ensemble/lib/action/action_invokable.dart, modules/ensemble/lib/action/bottom_sheet_actions.dart, modules/ensemble/lib/action/change_locale_actions.dart, modules/ensemble/lib/ensemble.dart, modules/ensemble/lib/ensemble_app.dart, modules/ensemble/lib/ensemble_provider.dart, modules/ensemble/lib/framework/action.dart, modules/ensemble/lib/framework/config.dart, modules/ensemble/lib/framework/data_context.dart, modules/ensemble/lib/framework/event/change_locale_events.dart, modules/ensemble/lib/framework/i18n_loader.dart, modules/ensemble/lib/framework/model/supported_language.dart, modules/ensemble/lib/framework/widget/widget.dart, modules/ensemble/lib/provider.dart, modules/ensemble/pubspec.yaml
- Exposing actions to setLocale and clearLocale. I used this vs setLanguage because it currently set both Language and Locale. Separating them out is harder and can be done later.
- Action will call Ensemble().setLocale/clearLocale. It is made this way so a Flutter app can also call Ensemble function from Flutter code.
- Ensemble dispatch an Event, which EnsembleApp will listen and rebuild the entire app.
- Also expose "app.supportedLocales" which returns the supported languages.
=> Enabling overriding Locale at runtime

modules/ensemble/lib/util/input_validator.dart, modules/ensemble/test/validators_test.dart
The phone validator function was coming from the following package:
and was accepting strings greater then 7 and less then 15 consisting only of digit with regExp "^\d{7,15}$" which is correct but the bug was in the function.
the function is removing the non-digit number then checking the phoneExp thats why it is returning true.
so am just using simple regExp function that will do the work using the above mentioned Expression and the message doesnt mattar, we are just returning the bool.
=> corrected the phone validator function for text input in form widget.

modules/ensemble/lib/widget/input/form_textfield.dart
Closes: https://github.com/EnsembleUI/ensemble/issues/1548
EDL:
```yaml
- TextInput:
label: Hello world
maxLength: 10
maxLengthEnforcement: none # none, enforced, truncateAfterCompositionEnds
- PasswordInput:
maxLength: 8
maxLengthEnforcement: enforced
```
=> TextInput/PasswordInput: maxLength and maxLengthEnforcement 

modules/ensemble/integration_test/local/customWidget_test.dart, modules/ensemble/integration_test/local/widgets/Custom Widget - onLoad.yaml, modules/ensemble/lib/framework/data_context.dart, modules/ensemble/lib/framework/definition_providers/provider.dart, modules/ensemble/lib/framework/widget/widget.dart, modules/ensemble/lib/layout/templated.dart, modules/ensemble/lib/widget/custom_widget/custom_widget.dart
- When Custom Widget reuses its state, onLoad is not being called. We just need to move from initState() to didChangeDependency().
- While on it, noticed it was called multiple times because API changes dispatch LOADING state, which is something we don't care from itemTemplate's perspective
- While at it, fixed the issue with dotEnv in local provider.
=> #1582 Fixed Custom Widget's onLoad not dispatching in some ocassion

modules/ensemble/lib/widget/carousel.dart
ticket: https://github.com/EnsembleUI/ensemble/issues/1652
there could be four possible values for `scrollType` which is `bouncing || clamping || neverScrollable || alwaysScrollable` and default for iOS is `bouncing ` and for other is `clamping`.
Example EDL: 
```yaml
Carousel:
id: carousel
styles:
height: 100
gap: 20
layout: auto
borderColor: blue
padding: 10
currentIndex: 0
indicatorType: rectangle
indicatorPosition: topCenter
enlargeCenterPage: true
indicatorWidth: 10
indicatorHeight: 2
indicatorColor: green
autoplay: true
autoplayInterval: 3
scrollType: neverScrollable    # it could be bouncing || clamping || neverScrollable || alwaysScrollable
```
=> added support for property on Carousel to disable the swipe action

modules/ensemble/lib/widget/collapsible.dart, modules/ensemble/lib/widget/widget_registry.dart, modules/ensemble/pubspec.yaml
requested ticket: https://github.com/EnsembleUI/ensemble/issues/1629
TODO:
- right now  it just supports `items` not `itemTemplate`, will create ticket for that as I tried to implement it for now but it was not happening, maybe I was missing something and it was taking a lot of time. Will work on it in free time.
Example EDL: 
```yaml
Collapsible:
isAccordion: true
headerStyle:
backgroundColor: red
borderColor: green
borderColorOpened: red
backgroundColorOpened: grey
borderWidth: 5
borderRadius: 5
bodyStyle:
backgroundColor: white
borderColor: green
borderWidth: 3
horizontalPadding: 20
flipRightIconIfOpen: true
openAndCloseAnimation: true
paddingBetweenOpenSections: 10
paddingBetweenClosedSections: 10
items:
- header: 
Text: 
text: "Section 1 Heading"
body: 
Text: 
text: "Section 1 body" …
```
=> added colapsible widget

modules/ensemble/lib/framework/apiproviders/api_provider.dart, modules/ensemble/lib/framework/apiproviders/http_api_provider.dart, modules/ensemble/lib/framework/data_context.dart, modules/ensemble/pubspec.yaml, modules/ensemble_ts_interpreter/lib/api.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1649
Example EDL:
```yaml
getProducts:
url: https://postman-echo.com/post
method: POST
manageCookies: true  # default is false
onResponse: |
console.log(response.body);
console.log(response.headers['set-cookie']); // just to confirm
console.log(response.cookies); 
```
=> added cookie property in api body

modules/ensemble/lib/widget/visualization/chart_js.dart, modules/js_widget/lib/src/mobile/js_widget.dart, modules/js_widget/lib/src/web/js_widget.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1685
Tested with the Android build and well with CanvasKit and HTML.
Example EDL:
```yaml
- ChartJs:
onTap: 
executeCode:
body: | 
console.log("hi");
config: |
{
"type": "pie",
"data": {
"labels": ["Red", "Blue", "Yellow"],
"datasets": [{
"data": [300, 50, 100],
"backgroundColor": [
"rgb(255, 99, 132)",
"rgb(54, 162, 235)",
"rgb(255, 205, 86)"
]
}]
}
}
```
=> added onTap feature for chartJS

modules/ensemble/lib/framework/apiproviders/http_api_provider.dart
before we were just using `application/json` unless some other `conten-Type` is not specified but `application/x-www-form-urlencoded` requires special type of formating like `key1=value1&key2=value2` to make it work.
Ticket: https://github.com/EnsembleUI/ensemble/issues/1741
=> [1741] updated api to support urlencoded content type

modules/auth/lib/signin/auth_manager.dart, modules/auth/lib/signin/widget/sign_in_with_apple.dart
Updated to support firebase type.  
Inspired by:
https://firebase.google.com/docs/auth/ios/apple#sign_in_with_apple_and_authenticate_with_firebase
https://medium.com/@muhammad.fathy/resolving-the-firebase-auth-invalid-credential-invalid-oauth-response-from-apple-com-6bca6b6a8575
Issue:
I've been able to use Firebase Auth with SignInWithGoogle successfully.  However, SignInWithApple gives the following error when trying to signin using a simulator 
Error:
`flutter: Async Error: [firebase_auth/invalid-credential] Invalid OAuth response from apple.co`
=> add support for firebase auth requirements for apple signon

modules/ensemble/lib/widget/checkbox.dart, modules/ensemble/lib/widget/input/dropdown.dart, modules/ensemble/lib/widget/input/form_date.dart, modules/ensemble/lib/widget/input/form_time.dart, modules/ensemble/lib/widget/radio/radio_button.dart, modules/ensemble/lib/widget/radio/radio_group.dart, modules/ensemble/lib/widget/switch.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1853
EDL:
```yaml
- Form:
children:
- TextInput:
id: testPassInp
required: true
maxLength: 3
maxLengthEnforcement: none
requiredMessage: Hello world
styles:
errorStyle:
color: pink
labelStyle:
color: transparent
- Dropdown:
required: true
requiredMessage: hello world
label: Select Items
styles:
errorStyle:
color: blue
items:
- Hello
- World
- RadioGroup:
id: radioIdGroup
required: true
requiredMessage: Radio required
styles:
errorStyle:
color: blue
items:
- label: Test
value: test
- label: World
value: world
- TextInput:
id: testPassInp
required: true
requiredMessage: kasdhaskjdhkjasd
maxLength: 3
maxLengthEnforcement: none
styles:
labelStyle:
color: transparent
- Button:
label: Submit Form
submitForm: true
```
Demo Video: …
=> added requiredMessage and errorStyle for form fields

modules/ensemble/lib/framework/menu.dart, modules/ensemble/lib/framework/view/bottom_nav_page_group.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1855
=> Added Switch screen evaluation for BottomNavbar

modules/location/lib/widget/maps/maps.dart, modules/location/lib/widget/maps/maps_state.dart
fixes: https://github.com/EnsembleUI/ensemble/issues/1764
- Added `fixedMarker` and `draggableMarker` properties to the Map widget.
- `fixedMarker`: When enabled, this keeps the marker fixed at the center of the map, following the movement of the map as the user moves.
- `draggableMarker`: When enabled, this allows the marker to be dragged by the user to any location on the map.
- The updated latitude and longitude of the marker can be accessed via the `onCameraMove` action.
`fixedMarker`
https://github.com/user-attachments/assets/5ab2fdda-dce3-4f70-9161-6edc2babd362
`draggableMarker`
https://github.com/user-attachments/assets/1184df6f-f1dd-4041-b7a3-2a631939d762
=> feat(maps): add fixedMarker and draggableMarker functionality to Map Widget

modules/ensemble/lib/widget/webview/native/webviewstate.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1882
- Fixed that bug for Android.
- Also removed the deprecated properties and used the new ones.
Test:
- On Android opening external links other then the one we pass at the begining.
- Tested the same for iOS.
- Also tested webview with KPN Inhome.
=> [1882] Fixed External links are not opening in a webview for Android

modules/ensemble/lib/ensemble.dart, modules/ensemble/lib/framework/ensemble_config_service.dart, modules/ensemble/lib/framework/secrets.dart
Before updated structure for local provider, the config used to be null for preview app, and we were allowing it to proceed. 
But now, we were throwing an error, that's why it was causing issues with the preview app as it doesn't have config, and we are accessing it in some places just to check whether it's a local or ensemble provider. 
That's why we need the config now. So, instead of throwing an error, we are now sending the default.
=> fix: ensure EnsembleConfigService is initialized before accessing config

starter/lib/generated/ensemble_modules.dart
Auth module was initializing firebase differently then the other modules, and if user only enable the Auth module, it causes the duplicate firebase app error
This PR insures, to initialize the user firebase app before running the ensemble firebase
=> fix: include useAuth in module initialization check

modules/ensemble/lib/layout/tab/base_tab_bar.dart
Github ticket: https://github.com/EnsembleUI/ensemble/issues/1876
String Expressions was not being passed into ```ScopeManager.DataContext.eval()```.
Passing through it before rendering fixed the issue.
for this yaml code:
```
View:
header:
titleText: TaBBar Test
onLoad: |
ensemble.storage.activeOrders = [
1,2,3,4,5
];
body:
TabBar:
items:
- label: Active ${ensemble.storage.activeOrders.length}
widget:
Text:
text: ${ensemble.storage.activeOrders.length}
- label: Completed ${ 1 + 2 }
widget:
Text:
text: ${ 1 + 2 }
```
=> TabBar Item will now evalute string expressions

modules/ensemble/lib/layout/form.dart, modules/ensemble/lib/widget/button.dart, modules/ensemble/lib/widget/helpers/form_helper.dart, modules/ensemble/lib/widget/input/form_textfield.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1867
Demo Video:
https://github.com/user-attachments/assets/b6977565-88c6-4d38-8ac5-6e15265f526c
CC: @ridsashabbir @sharjeelyunus
=> new properties to form and TextInput widget for keyboard dissmiss control

modules/ensemble/lib/framework/widget/widget.dart, modules/ensemble/lib/util/utils.dart, modules/ensemble/lib/widget/helpers/controllers.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1841
Testing Schema:
- For double opacity:
```
- Form:
id: getStartedForm
onSubmit:
executeCode:
body: |
console.log(test.value);
styles:
gap: 24
children:
- TextInput:
opacity: 0.3
styles: 
id: test
label: hello
- TextInput:
id: test1
label: world
- Button: 
label: submit
submitForm: true
```
- For Integer Opacity:
```
- Form:
id: getStartedForm
onSubmit:
executeCode:
body: |
console.log(test.value);
styles:
gap: 24
children:
- TextInput:
opacity: 1
styles: 
id: test
label: hello
- TextInput:
id: test1
label: world
- Button: 
label: submit
submitForm: true
```
CC: @ridsashabbir @sharjeelyunus
=> Fix: Opacity Crashing for integer value

modules/auth/pubspec.yaml, modules/ensemble/lib/action/saveFile/save_mobile.dart, modules/ensemble/pubspec.yaml, modules/ensemble_bluetooth/pubspec.yaml, modules/otp_pin_field/android/build.gradle, modules/otp_pin_field/android/src/main/kotlin/com/shivam/otp_pin_field/AppSignatureHelper.kt, modules/otp_pin_field/android/src/main/kotlin/com/shivam/otp_pin_field/OtpPinFieldPlugin.kt, modules/otp_pin_field/pubspec.yaml
Flutter 3.29 comes with deprecation of many plugins
- Changed from pub.dev package (0.5.2) to direct git reference because:
1. The pub version uses deprecated Flutter plugin registration system (`Registrar` and `PluginRegistrantCallback`)
2. Flutter 3.29.0 removed these deprecated APIs in favor of new embedding system
3. The git main branch has updated code using new Flutter plugin APIs but new version has not been published to pub.dev with these updates yet, for that issue is there (https://github.com/fluttercommunity/flutter_workmanager/issues/588)
- Removed `registerWith` method and `Registrar` constructor.
- Added null safety check for `signingInfo.apkContentsSigners` to fix type mismatch errors
- No changes to core feature implementation or business logic
- Original package (2.0.3) …
=> flutter 3.29 build issues solved

modules/ensemble/lib/framework/ensemble_widget.dart, modules/ensemble/lib/framework/widget/widget.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1874
- Used existing `testId` property in Ensemble widgets.
- Wrap returned widget with [KeyedSubtree](http://api.flutter.dev/flutter/widgets/KeyedSubtree-class.html), using `testId` as its key.
Example EDL:
```yaml
Button:
testId: navigate_button
label: Navigate to Goodbye Screen
onTap:
navigateScreen:
name: Goodbye
```
Example Flutter Test code:
```dart
final navigateButtonFinder = find.byKey(
ValueKey('navigate_button'), 
skipOffstage: false
);
```
https://github.com/user-attachments/assets/e11ccf42-a6fb-4f5c-a6e6-c22c71f6b211
=> [1874] Added key to widgets

CHANGELOG.md, modules/auth/pubspec.yaml, modules/bracket/pubspec.yaml, modules/camera/pubspec.yaml, modules/chat/pubspec.yaml, modules/connect/pubspec.yaml, modules/contacts/pubspec.yaml, modules/deeplink/pubspec.yaml, modules/ensemble/CHANGELOG.md, modules/ensemble/pubspec.yaml, modules/ensemble_bluetooth/pubspec.yaml, modules/ensemble_network_info/pubspec.yaml, modules/file_manager/pubspec.yaml, modules/firebase_analytics/pubspec.yaml, modules/location/pubspec.yaml, modules/moengage/pubspec.yaml, starter/pubspec.yaml
=> chore(release): publish packages

modules/ensemble/lib/action/device_security.dart, modules/ensemble/pubspec.yaml
Ticket: https://github.com/EnsembleUI/ensemble/issues/1898
Added `correctlyInstalled` property in `deviceSecurity` action to check whether the app is downloaded from official sources.
Testing EDL:
```
Button:
label: Check Device Security
onTap:
deviceSecurity:
onSuccess:
executeCode:
body: |-
console.log('Device is tempered: ' + event.data.correctlyInstalled);
```
Note: I tested in debug mode so I will always get `false` in response, We can test this property correctly on deployed apps.
CC: @sharjeelyunus
=> added correctlyInstalled property in deviceSecurity action

modules/camera/lib/camera.dart
Basically the issue was, when we open camera first time, and then closing it, it wasn't disposing the camera, so when we open it again the camera was locked so it was throwing error. This is happening only on android web, and only in release mode.
REF: https://discord.com/channels/1031982848485359626/1345056316141600798
=> Fix: dispose existing camera controller before initializing a new one

modules/ensemble/lib/layout/list_view.dart
Github ticket: https://github.com/EnsembleUI/ensemble/issues/1817
ListView `styles` has `gap` Property that adds vertical padding between children 
Note that property adds gap below the element except for the last item.
Yaml:
```
View:
header:
title: Listview
onLoad:
invokeAPI:
name: getPeople
body:
ListView:
id: listView
styles:
gap: 12
item-template:
data: ${getPeople.body.users}
name: user
template:
Text:
text: ${user.email}
API:
getPeople:
url: https://dummyjson.com/users
method: GET
```
=> List view gap

modules/ensemble/lib/ensemble.dart, modules/ensemble/lib/framework/config.dart
Now `app.language` can be used to get the current selected language of the phone.
Example Usage:
```
View:
styles:
useSafeArea: true
header:
titleText: Home
onLoad:
executeCode:
body: |
console.log(app.languages)
console.log(app.language)
body:
Column:
styles:
padding: 24
gap: 8
children:
- Text:
text: App Languages
styles:
textStyle:
fontSize: 20
- Text:
text: ${app.languages}
- Text:
text: App Language
styles:
textStyle:
fontSize: 20
- Text:
text: ${app.language}
```
Screenshot Result:
CC: @kmahmood74
=> added `language` property to get current selected language

modules/ensemble/lib/framework/apiproviders/firestore/firestore_app.dart
Discovered an issue with firestore queries with startAfter as timestamp.   The field value at runtime is FirestoreTimestamp and this causes an error from the firestore api.   This pr unwraps startAfter, startAt, endBefore and endAt.
=> bugfix - addl firestore fields req unwrapping

modules/ensemble/lib/ensemble_app.dart, modules/ensemble/lib/framework/widget/screen.dart
A solution to the duplicate GlobalKey error when using 2 EnsembleApp in a native flutter app.
Discord discussion: https://discord.com/channels/1031982848485359626/1351798223781625926/1351798223781625926
The approach we are now using is:
- making the rendering of the screen in `EnsembleApp` optional by passing a child widget from the host app, so that we do all the initialization for ensemble and return that widget back to the host app, so that it works as it is.
- And then just use `Screen` widget at multiple places as many times we want for specific Ensemble screens without the duplicate globalKey error.
Below is a recording with multiple EnsembleApp.
- From home tab going to media details screen that shows match stats in ensemble `Screen`
- From sports tab, we are opening Ensemble …
=> Making rendering of the screen optional in ensembleApp

modules/ensemble/lib/framework/view/page_group.dart
Previously `footer` required height in `Drawer` Menu.
Wrapped it in `EXPANDED` so it may take the available space.
=> Footer height Requirement for Drawer

modules/ensemble/lib/ensemble.dart, modules/ensemble/lib/ensemble_app.dart, modules/ensemble/lib/widget/external_widget.dart, modules/ensemble/lib/widget/widget_registry.dart
User launches a Flutter widget from within an Ensemble screen.
Flow:
- User Register Native Flutter widget with EnsembleApp passing it to new property `externalWidgets`
- Use `ExternalWidget` in Ensemble screen, with the name of the Flutter widget with which they register it.
- Pass the values from Ensemble to Flutter widget using `Inputs`.
- Define events to get back value sform Flutter widgets to Ensemble screen using these callbacks
=> [Feat] Added new widget `ExternalWidget`

modules/ensemble/lib/action/device_security.dart
- Added utility methods to retrieve local package name and signature.
- Updated validation logic to compare current package name and signature against the evaluated values from the context.
=> fix: enhance package name and signature validation in DeviceSecurity

modules/file_manager/pubspec.yaml
Build system is failing with this error, seems like file_ficker `5.2.10` is deprecated, upgrading it to the latest version
```
Package file_picker:windows references file_picker:windows as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of file_picker to either avoid referencing a default implementation via `platforms: windows: default_package: file_picker` or add an inline implementation to file_picker via `platforms: windows:` `pluginClass` or `dartPluginClass`.
Note: /Users/builder/.pub-cache/hosted/pub.dev/google_mlkit_face_detection-0.12.0/android/src/main/java/com/google_mlkit_face_detection/FaceDetector.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details. …
```
=> chore: update file_picker dependency to version 10.1.2

modules/ensemble/lib/ensemble.dart, modules/ensemble/lib/framework/assets_service.dart
When pointing towards `local`
- the config map didn't find the `envVariables` key in `appConfig.json` and upon that, it threw an error `the appConfig.json file not found`. fixing it using a condition
When pointing towards `ensemble`
- If we create a new application on Studio, and it doesn't have any environment variables available in it, it will throw a screen error `Null check operator used on a null value`
=> [Bug] Fixed `null check operator` error upon loading assets

modules/ensemble/lib/framework/view/page.dart
When we have teh heder, while we are scrolling we were getting error `type 'int' is not a subtype of type 'double'`, because `clamp` fucnitno expect double value but we were giving the int value.
=> [Bug] fixed the double error in header

modules/ensemble/lib/action/app_setting.dart, modules/ensemble/lib/framework/action.dart, modules/ensemble/lib/framework/device.dart, modules/ensemble/lib/screen_controller.dart, modules/ensemble/pubspec.yaml
Ticket: https://github.com/EnsembleUI/ensemble/issues/1976
Schema PR: https://github.com/EnsembleUI/ensemble-web-studio/pull/1632/files
docs: https://github.com/EnsembleUI/ensemble_docs/pull/81
We were using `app_settings` package which was not supporting major targets on iOS as described in the description of hte properties as they are only supported for android: https://github.com/spencerccf/app_settings/blob/master/lib/src/app_settings_type.dart
So changed the package to use: https://pub.dev/packages/open_settings_plus
It supports many targets, keeping the exsiting one we were supporting back as well.
Also the EDL is same as before for backward compatibility.
```
View:
header:
title: App Settings
styles:
scrollableView: false
body:
Column:
styles:
gap: 24
padding: 24
mainAxis: start …
```
=> [Fix] `openAppSettings` was not working on iOS to open wifi target

modules/ensemble/lib/widget/input/slider/slider.dart, modules/ensemble/lib/widget/input/slider/slider_controller.dart, modules/ensemble/lib/widget/input/slider/slider_state.dart
**Overview:**
This PR adds range slider functionality to the existing EnsembleSlider widget, allowing users to select both a lower and upper value within a specified range. This implementation preserves all existing functionality while adding new capabilities with minimal API changes.
**Features**
- Toggle between single-value and range-slider modes using the enableRange property
- Support for setting start and end values individually or via a single initialRangeValues property
- Compatibility with existing styling composites (track, thumb, tick marks, overlay, value indicators)
- Uses the existing onChange event handler for both slider types for API consistency
Sample EDL & Emulator Output:
=> Range slider

modules/ensemble/lib/action/action_invokable.dart, modules/ensemble/lib/action/file_picker_action.dart, modules/ensemble/lib/action/getLocation.dart, modules/ensemble/lib/framework/action.dart, modules/ensemble/lib/framework/stub/file_manager.dart, modules/ensemble/lib/screen_controller.dart, modules/file_manager/lib/file_manager.dart
This PR addresses issues where the following actions are not functioning correctly when used in JS
=> Fix Invokable actions [JS Compatibility]

modules/ensemble/lib/action/action_invokable.dart, modules/ensemble/lib/action/key_chain_actions.dart, modules/ensemble/lib/action/secure_storage.dart, modules/ensemble/lib/framework/action.dart, modules/ensemble/lib/framework/data_context.dart, modules/ensemble/lib/framework/encrypted_storage_manager.dart, modules/ensemble/lib/framework/keychain_manager.dart, modules/ensemble/pubspec.yaml
Ticket: https://github.com/EnsembleUI/ensemble/issues/1984
docs: https://github.com/EnsembleUI/ensemble_docs/pull/82
Schema: https://github.com/EnsembleUI/ensemble-web-studio/pull/1639
When we were using `ensemble.storage.variable`, it was storing user information in plain text in the device, which is not ideal way to do it as it may caontain sensitive information.
So we can use `keyChain` & `keyStore` for secure storage, for which we already have action `saveKeyChain` to store the values, it can be used in the YAML and JS, both ways.
But we didn't had any way to read those values back, so i introduced a new action `readKeyChain`. It is only available in YAML, as this calls a async function whose return type is Future and we use callbacks to handle the result. Our JS is sync and we cannot …
=> [Feat] Add secureStorage actions

modules/ensemble/lib/widget/input/form_date.dart
This PR introduces a new textStyle property to style the selected date value in the date widget. To maintain backwards compatibility, the implementation includes logic to fall back to using labelStyle for styling date values when textStyle is not specified. This ensures existing applications continue to work as expected without modifications.
Sample EDL and output
=> Added Textstyle property for date widget

modules/ensemble/lib/action/stripe_actions.dart, modules/ensemble/lib/framework/action.dart, modules/ensemble/lib/framework/stub/stripe_manager.dart, modules/ensemble/lib/module/stripe_module.dart, modules/ensemble_stripe/README.md, modules/ensemble_stripe/lib/ensemble_stripe.dart, modules/ensemble_stripe/lib/stripe_manager.dart, modules/ensemble_stripe/melos_ensemble_stripe.iml, modules/ensemble_stripe/pubspec.yaml, starter/android/app/build.gradle, starter/android/app/src/main/res/values-night/styles.xml, starter/android/app/src/main/res/values/styles.xml, starter/ensemble/ensemble-config.yaml, starter/ios/Runner/AppDelegate.swift, starter/lib/generated/ensemble_modules.dart, starter/package.json, starter/pubspec.yaml, starter/scripts/modules/enable_stripe.dart, starter/src/modules_scripts.ts
- Introduced ShowPaymentSheetAction for displaying Stripe payment sheets.
- Implemented StripeManager interface with a stub and a real implementation.
- Added configuration support for Stripe in ensemble-config.yaml.
- Updated README with usage instructions and examples for Stripe integration.
- Registered Stripe module in the Ensemble framework.
Stripe is automatically initialized when the module is enabled. Add your Stripe configuration to `ensemble-config.yaml`:
```yaml
stripe:
enabled: true
publishableKey: "pk_test_your_publishable_key_here"
stripeAccountId: "acct_optional_account_id"  # Optional
merchantIdentifier: "merchant.com.yourapp"   # Optional, for Apple Pay
```
Display the native Stripe payment sheet.
```yaml
showPaymentSheet:
clientSecret: "pi_client_secret_here" …
```
=> feat(stripe): add Stripe payment integration module

modules/ensemble/lib/widget/helpers/controllers.dart
Dropdown is not showing `aria-label` if there is no semantics label, and no label of dropdown
If there is no semantics label, and no label, then use the label of the value
e.g
this dropdown, does not have the label, or the semantics label, in this case, its value is en, and label for this value is `r@kpn.languages.english` => English
So the `aria-label` in this case should be English
```yaml
Dropdown:
items:
- { label: "r@kpn.languages.english", "value": "en" }
- { label: "r@kpn.languages.dutch", "value": "nl" }
value: ${app.locale.languageCode}
onChange: |
ensemble.setLocale({ "languageCode": event.data.value });
ensemble.storage.userSelectedLanguage = event.data.value;
```
- Improved the method for retrieving labels based on current values by adding robust checks for both direct …
=> feat(widget): enhance semantics label retrieval logic

modules/ensemble/pubspec.yaml, packages/ensemble_otp/CHANGELOG.md, packages/ensemble_otp/README.md, packages/ensemble_otp/ios/Classes/OtpPinFieldPlugin.m, packages/ensemble_otp/ios/Classes/OtpPinFieldPlugin.swift, packages/ensemble_otp/ios/ensemble_otp.podspec, packages/ensemble_otp/pubspec.yaml
- Fixed iOS build errors related to Swift header imports.
- Corrected podspec configuration for proper Swift module generation.
- Updated method channel naming for consistency.
- Resolved podspec name mismatch issues.
- Added proper Swift header configuration in podspec.
=> chore(release): update ensemble_otp to version 1.0.2

modules/ensemble/lib/action/wakelock_action.dart, modules/ensemble/lib/framework/action.dart, modules/ensemble/lib/framework/device.dart, modules/ensemble/pubspec.yaml, starter/android/build.gradle, starter/android/gradle/wrapper/gradle-wrapper.properties
Ticket: https://pub.dev/packages/wakelock_plus
Example EDL of action:
```yaml
wakelock:
enable: true # could be true and false
onComplete: |
console.log('Wakelock enabled - screen will stay awake');
onError: |
console.log('Failed to enable wakelock');
```
And we can get the current status from using `ensemble.device.wakelockEnabled`
Its latest version required `package_info_plus ` to be upgraded, and `package_info_plus ` required the latest Kotlin and gradle version.
=> added always on display action and uprgraded gradle version
