EnsembleUI/ensemble

assets/schema/ensemble_schema.json, lib/layout/form.dart, lib/util/layout_utils.dart, lib/widget/form_helper.dart, lib/widget/form_textfield.dart, lib/widget/widget_registry.dart, test/widget/invokable_test.dart
=> - rename Password to PasswordInput

lib/framework/widget/icon.dart, lib/framework/widget/view.dart, lib/page_model.dart, lib/widget/ensemble_icon.dart, lib/widget/image.dart
- Screen's backgroundImage can now reference local asset image
- Image can now reference local asset image
=> Local assets now work with Icon, Image, and screen's background

assets/schema/ensemble_schema.json, lib/framework/action.dart, lib/framework/data_context.dart, lib/screen_controller.dart, lib/util/upload_utils.dart, lib/util/utils.dart, pubspec.yaml
Ticket : https://github.com/EnsembleUI/ensemble/issues/129
Sample YAML configuration
```yaml
Button:
label: Pick
onTap:
action: uploadFiles
id: filePicker
url: https://5004-103-238-108-177.ngrok.io/core/file/multiple_upload/
options: 
allowMultiple: True
allowExtensions: 
- jpg
- pdf
onComplete: |
//@code
ensemble.debug(filePicker.files[0]['name'])
onError: |
//@code
ensemble.debug('Failed to upload files')
```
=> File upload Action 

assets/schema/theme_schema.json, lib/ensemble_theme.dart, lib/widget/form_helper.dart
Ticket : https://github.com/EnsembleUI/ensemble/issues/260
Sample code:
- TextInput:
label: Input
labelHint: Hello
backgroundColor: green
required: true
=> https://github.com/EnsembleUI/ensemble/issues/260

assets/schema/ensemble_schema.json, lib/framework/action.dart, lib/framework/data_context.dart, lib/screen_controller.dart, lib/util/upload_utils.dart, lib/util/utils.dart
TIcket: #258 
Added two new parameters:
- maxFileSize 
- overMaxFileSizeMessage
Updated one parameter 
- UploadUrl => apiName
Users can expect the same functionality in `invokeAPI`, like setting url, method, headers, inputs.
=> File enhancements

lib/widget/form_textfield.dart
Ticket : https://github.com/EnsembleUI/ensemble/issues/219
Ticket Url : [https://github.com/EnsembleUI/ensemble/issues/219](url)
Sample YAML configuration
- TextInput:
label: Example 1
hintText: Placeholder value
required: true
maxLines: 5
=> max line added

assets/schema/theme_schema.json, lib/framework/theme/theme_loader.dart, lib/widget/input/dropdown.dart, lib/widget/input/form_helper.dart, lib/widget/input/form_textfield.dart
=> Fixed #287. See inline comment

lib/layout/box/box_utils.dart
Ticket: #393 
Fixed the gap issue for the custom widget
Sample YAML:
```
View:
styles:
useSafeArea: true
body:
Column:
styles: { gap: 8, backgroundColor: yellow }
children:
- Column:
visible: false
children:
- Text:
text: I am invisible
- Column:
visible: false
children:
- Text:
text: I am invisible
- Text:
visible: true
text: I am invisible
- CustomHeader:
- Column:
visible: false
children:
- Text:
text: I am invisible
- Column:
visible: true
children:
- Text:
text: I am visible
CustomHeader:
body:
Column:
styles: { gap: 8, backgroundColor: 0xFF0F0E1C }
children:
- Row:
styles: { mainAxis: spaceBetween, crossAxis: center }
children:
- Text:
text: Transactions
styles: { padding: 8, fontSize: 18, color: white }
- Column:
onTap:
navigateModalScreen:
name: Menu
children:
- Image:
source: …
```
=> Fix custom widget gap issue

lib/framework/view/page.dart
=> Evaluating header's title

lib/layout/ensemble_page_route.dart, lib/screen_controller.dart
```bash
flutter test .\integration_test\login_test.dart --dart-define=transitions=false
```
=> added env variable to disable transitions

lib/framework/theme/default_theme.dart, lib/framework/theme/theme_loader.dart, lib/widget/widget_util.dart
Theming bugs #469 
*New: Inline google fonts support
=> fix default style

assets/schema/ensemble_schema.json, lib/widget/maps/maps.dart, lib/widget/maps/maps_overlay.dart, lib/widget/maps/maps_state.dart, lib/widget/maps/maps_utils.dart, lib/widget/widget_registry.dart, pubspec.yaml
Use "Maps" widget. ("Map" points to legacy Map)
=> Add Google Maps

lib/screen_controller.dart, pubspec.yaml
@vusters 
Before merging this PR, the ensemble-ts-interpreter's [PR](https://github.com/EnsembleUI/ensemble_ts_interpreter/pull/17) needs to be merged.
=> Bumped intl package to v0.18.0

lib/framework/data_context.dart
Fixes: [#497](https://github.com/EnsembleUI/ensemble/issues/497)
The `dart developer log` is not working. I changed it to `debugPrint` from the `foundation` package
Tested it in both `development` and `release` build mode
=> Fixed ensemble.debug issue

lib/ensemble_app.dart, lib/framework/view/page.dart, lib/framework/widget/screen.dart, lib/util/unfocus.dart
Ticket: #538 
In this PR, I fixed the following
1. Background content will not be resized when keyboard pops-up
2. Keyboard will be dismissed when clicking outside in the non-interactive widgets
=> Fixed keyboard issues

assets/schema/ensemble_schema.json, lib/framework/data_context.dart, lib/widget/staggered_grid.dart, lib/widget/widget_registry.dart, pubspec.yaml
In this PR, I added Staggered Grid View.
```yaml
body:
StaggeredGrid: 
styles: { horizontalGap: 5, verticalGap: 7 }
item-template:
data: ${getImages.body}
name: item
template:
CustomCard:
inputs:
item: ${item}
onItemTap: |
//@code
console.log("Staggered Grid Item TAPPED - " + event.data.selectedItemIndex);
```
=> Added staggered grid view widget

assets/schema/ensemble_schema.json, integration_test/defaultApp_test.dart, integration_test/framework/test_helper.dart, lib/widget/carousel.dart, test/widget/dropdown_test.dart
In this PR, I added autoplay and duration to the carousel widget
=> Add autoplay to carousel and update schema

assets/schema/ensemble_schema.json, lib/framework/action.dart, lib/screen_controller.dart
Ticket: #625
```yaml
Button:
label: Show Bottom Modal Sheet
onTap:
showBottomModal:
widget: HotelCard
styles: { backgroundColor: green, barrierColor: orange }
options: { enableDrag: true, enableDragHandler: true }
```
=> Add modal bottom sheet

assets/schema/ensemble_schema.json
Added schema for this issue - #669
Original PR - #676
=> feat(schema): add number, text and few other text input types

assets/schema/ensemble_schema.json
Ticket
https://github.com/EnsembleUI/ensemble-web-studio/issues/445
https://github.com/EnsembleUI/ensemble-web-studio/issues/465
=> added elseif and else to schema

assets/schema/ensemble_schema.json
Surfaced by https://github.com/EnsembleUI/ensemble-web-studio/pull/450
=> Fix schema for Checkbox, Dropdown, and Date

lib/ensemble.dart, lib/module/auth_module.dart, lib/widget/stub_widgets.dart, lib/widget/widget_registry.dart
Related PR https://github.com/EnsembleUI/ensemble_module_auth/pull/1
=> Add stubs for SignInWithAuth0

lib/layout/list_view.dart
=> Fix list view on item tap issue

assets/schema/ensemble_schema.json, lib/framework/stub/oauth_controller.dart, lib/framework/view/page.dart
Ticket: #631 
Adding new property to header widget, set background when scrolled. Below is sample yaml.
```yaml
View:
styles:
useSafeArea: true
header:
title: Images
styles:
backgroundColor: white
surfaceTintColor: brown #new property
```
=> set header bg color on scroll

lib/framework/action.dart, lib/framework/data_context.dart, lib/framework/permissions_manager.dart
In this PR, I added the `saveToKeychain` method to NativeInvokable.
You can invoke the saveTokeychain method from an ensemble code block like this below
Ex:
`ensemble.saveTokeychain("token", "Abwexcxdfsdfsdf");`
=> Add saveToKeychain method

lib/ensemble.dart, lib/framework/data_context.dart
Context: https://discord.com/channels/1031982848485359626/1133531971864248340
=> fixed firebase web un-initialization

lib/framework/action.dart, lib/framework/data_context.dart
Ticket: #730 
Added clearKeychain method and update saveToKeychain
=> Update Keychain service

lib/framework/view/bottom_nav_page_group.dart
=> Fix floating action button icon not rendering issue

assets/schema/ensemble_schema.json, lib/widget/box.dart, lib/widget/loading_container.dart, lib/widget/widget_registry.dart, pubspec.yaml
Ticket: #716 
**Sample YAML**:
```yaml
View:
header:
title: LoadingContainer
styles:
body:
Column:
styles:
gap: 16
padding: 30
crossAxis: center
mainAxis: center
children:
- LoadingContainer:
id: loadingWidget
isLoading: false
useShimmer: true
widget:
Text:
id: dataId
text: Data State
loadingWidget:
Progress:
display: circular
styles:
size: 24
- Button:
label: Change State
onTap: |
//@code
loadingWidget.isLoading = !loadingWidget.isLoading;
```
**Experiment**:
Here, I created a two widget.
1. LoadingContainer
2. Box
In the `LoadingContainer`, if the useShimmer is true. I'll simply wrap the loading widget with Shimmer.
`Box` widget is used to create simple box like Container widget in Flutter. Internally, I'm using BoxWrapper with BoxController to style it. 
```yaml …
```
=> WIP: Add LoadingContainer widget

lib/framework/view/page.dart, lib/framework/view/page_group.dart, lib/framework/widget/custom_view.dart
Ticket: [#775](https://github.com/EnsembleUI/ensemble/issues/775)
=> Sidebar menu item icon issue

assets/schema/ensemble_schema.json, lib/layout/tab_bar.dart
Ticket: [#774](https://github.com/EnsembleUI/ensemble/issues/774)
Added the following properties 
1. `activeTabBackgroundColor` 
2. `indicatorSize` (`tab` | `label`) - For more info (https://api.flutter.dev/flutter/material/TabBar/indicatorSize.html#:~:text=The%20size%20of%20the%20selected,label.)
3. `tabItem` - For custom tab item
4. `changeTabItem` JS method - To change the tab item programmatically from JS.
Added support for `borderRadius` property. For inActiveTabBackgroundColor, use `tabBackgroundColor` instead.
**Custom TabItem widget and changeTabItem method**
```yaml
tabItem:
CustomTabItem:
CustomTabItem:
Row:
styles:
gap: 12
children:
- Icon:
icon: star
styles: { size: 18 }
- Text:
text: First Tab
```
```yaml
onTap: |
//@code
tabBarId.changeTabItem(1); // Pass Index of the Tab …
```
=> Added few more properties for TabBar widget

lib/layout/tab_bar.dart
It fixes the following PRs #791 #792
=> Update tab bar selection and dividerColor

lib/framework/action.dart, lib/framework/view/bottom_nav_page_group.dart, lib/framework/view/page.dart, lib/framework/view/page_group.dart, lib/framework/widget/error_screen.dart, lib/layout/box/base_box_layout.dart, lib/layout/helper/layout_helpers.dart, lib/widget/helpers/pull_to_refresh_container.dart
=> Fix bottom nav bar content not to reload when clicking the bottom nav bar items

assets/schema/ensemble_schema.json, lib/ensemble_app.dart, lib/framework/action.dart, lib/framework/data_context.dart, lib/layout/box/base_box_layout.dart, lib/layout/box/box_layout.dart, lib/model/pull_to_refresh.dart, lib/screen_controller.dart, lib/util/http_utils.dart, lib/widget/helpers/pull_to_refresh_container.dart, lib/widget/image.dart
Ticket: [#798](https://github.com/EnsembleUI/ensemble/issues/798)
=> Add fallback property for Image widget

lib/ensemble_app.dart
=> Fix loadingBackgroundColor theme extension issue

lib/framework/view/bottom_nav_page_group.dart, lib/framework/view/page_group.dart
=> Fix bottom nav bar selected and extra space issue on top of the keyboard

assets/schema/ensemble_schema.json, lib/widget/helpers/widgets.dart, lib/widget/html.dart
https://github.com/EnsembleUI/ensemble/issues/834
=> issue: 834 support for onLinkTap for HTML widget

lib/layout/box/base_box_layout.dart
PR - [#838](https://github.com/EnsembleUI/ensemble/issues/838)
=> Change inkwell to gesture detector in base box layout widget

lib/action/bottom_modal_action.dart, lib/ensemble.dart, lib/framework/action.dart, lib/framework/data_context.dart, lib/framework/view/bottom_nav_page_group.dart, lib/framework/view/bottom_nav_page_view.dart, lib/framework/view/data_scope_widget.dart, lib/framework/view/page.dart, lib/screen_controller.dart, lib/widget/html.dart, lib/widget/input/form_textfield.dart, test/action_test.dart
`uploadFiles` action only supported uploading file which are passed through `pickFiles` action. 
Now it also supports uploading by just file path string and also list of file path string.
more context: https://discord.com/channels/1031982848485359626/1156652292523692052
=> Upload File supports file path string

lib/framework/data_context.dart, lib/framework/widget/has_children.dart, lib/layout/box/box_layout.dart, lib/layout/data_grid.dart, lib/layout/flow.dart, lib/layout/form.dart, lib/layout/stack.dart, lib/screen_controller.dart, lib/widget/carousel.dart, lib/widget/helpers/widgets.dart, lib/widget/image.dart, lib/widget/loading_container.dart, lib/widget/staggered_grid.dart
Ticket: #831
Fixed binging and eval for socket data.
=> socket bindings updated

assets/schema/ensemble_schema.json, lib/widget/carousel.dart
Ticket: [#845](https://github.com/EnsembleUI/ensemble/issues/845)
Discord: https://discord.com/channels/1031982848485359626/1158131183394226266/1158131183394226266
=> Add selectedItemIndex and enableInfiniteScroll setter for the carousel

assets/schema/ensemble_schema.json, lib/framework/widget/view_util.dart, lib/layout/grid_view.dart, lib/layout/list_view.dart, lib/layout/templated.dart, lib/page_model.dart
Ticket: #772
EDL Definition
```yaml
ListView:
onScrollEnd:
invokeAPI:
name: getPeople
onResponse: |
//@code
var results = getPeople.body.results;
var oldResults = ensemble.storage.users;
var total = oldResults.concat(results);
ensemble.storage.users = total;
item-template:
data: ${ensemble.storage.users}
name: user 
template:
Text:
text: ${user.name.first}
```
=> Infinite Scroll for ListView and GridView

assets/schema/ensemble_schema.json, lib/widget/helpers/widgets.dart, lib/widget/input/form_helper.dart, lib/widget/input/form_textfield.dart
Ticket - [#864](https://github.com/EnsembleUI/ensemble/issues/864)
Sample EDL:
```yaml
TextInput:
id: emailId
onDelayedKeyDuration: 1
onDelayedKeyPress: |
//@code
emailId.value = emailId.value;
styles:
{
floatLabel: true, # Defaults to False
label: '${emailId.value.length == 0 ? "" : "Name"}',
labelStyle:
{
fontWeight: semibold,
fontSize: 34,
color: green,
},
hintText: Enter your name,
}
```
=> Add floating label text and styles

assets/schema/ensemble_schema.json, lib/deep_link_manager.dart, lib/widget/input/form_helper.dart, lib/widget/input/form_textfield.dart
Ticket: [#864](https://github.com/EnsembleUI/ensemble/issues/864)
```yaml
TextInput:
id: emailId
styles:
{
label: Email,
floatLabel: true,
variant: box,
floatingLabelStyle:
{ fontWeight: semibold, fontSize: 34, color: green },
hintText: Enter your email,
focusedBorderColor: green,
enabledBorderColor: gray,
}
```
=> Added floatingLabelStyle property and updated decoration

assets/schema/ensemble_schema.json, lib/widget/calendar.dart
=> Fix Calendar

lib/framework/theme/theme_loader.dart, lib/framework/theme/theme_manager.dart, lib/util/utils.dart
=> Custom Text Style default color black.

assets/schema/ensemble_schema.json, lib/framework/menu.dart, lib/framework/view/bottom_nav_page_group.dart, lib/framework/view/page_group.dart
Ticket: #870
```yaml
ViewGroup:
Sidebar | Drawer | BottomNavBar:
reloadView: false | true
```
Completed Menus:
1. SideBar
=> WIP: Optimize screen rebuild for all the menu widgets

assets/schema/ensemble_schema.json, lib/widget/webview/native/webviewstate.dart, lib/widget/webview/web/webviewstate.dart, lib/widget/webview/webview.dart, pubspec.yaml
Added the cookie setter and clearcookies method. Ticket #899
=> Added cookies

lib/action/action_invokable.dart, lib/action/call_native_method.dart, lib/framework/action.dart, lib/framework/data_context.dart, lib/host_platform_manager.dart, lib/widget/avatar.dart, lib/widget/helpers/controllers.dart
In this PR, I added an action and methods to invoke the host platform methods
In **Ensemble**
**Action**:
```yaml
Button:
label: Call Todo Method
onTap:
callNativeMethod:
name: updateTodo
payload:
todoId: "ASDFSFDSWERWERWE",
todoName: "Learn EnsembleUI"
onComplete: |
//@code
console.log("Successfully called");
onError: |
//@code
console.log("Failed to call a method" + event.error);
```
**JS**:
```yaml
Button:
label: Call Todo Method
onTap: |
//@code
ensemble.callNativeMethod({
"name": "updateTodo", 
"payload": {
"todoId": "ASDFSFDSWERWERWE",
"todoName": "Learn EnsembleUI"
}
});
```
In the **Host Platform** (Android or iOS)
Register your flutter method channel and set the method handler with your method name.
Note: Set your flutter method channel name to `"com.ensembleui.host.platform"` …
=> Add callNativeMethod action and methods

lib/host_platform_manager.dart
=> Fix error handling for the callNativeMethod action

assets/schema/ensemble_schema.json, lib/framework/view/page.dart
Added additional callback `onMaxSize` and `onMinSize`
=> Enhance draggable footer

lib/framework/all_countries.dart
Updated the countries list json file.
=> All countries

ensemble/integration_tests/defaultApp/Conditional.yaml, ensemble/integration_tests/defaultApp/Invoke Api.yaml, integration_test/defaultApp_test.dart
Added invoke api integration testing. #904
=> integration testing

assets/schema/ensemble_schema.json, lib/framework/view/bottom_nav_page_group.dart
Ticket: #932 
```yaml
BottomNavBar:
styles:
{
shadowColor: green,
shadowRadius: 1,
shadowBlurRadius: 10,
shadowStyle: normal,
}
```
=> Add shadow to bottom nav bar

lib/framework/ensemble_widget.dart, lib/framework/widget/colored_box_placeholder.dart, lib/widget/avatar.dart, lib/widget/image.dart
Ticket: #890
Ticket: #925
Updated:
- Added width and height to the colored box placeholder widget
- Passed controller's placeholder color to the colored box placeholder widget
=> Fix svg image size when showing placeholder and refactor image type lookup

assets/schema/ensemble_schema.json, lib/widget/webview/native/webviewstate.dart, lib/widget/webview/webview.dart
Added headers in webview, similar to headers in api
=> Added Headers in webview

assets/schema/ensemble_schema.json, lib/widget/lottie/lottie.dart, lib/widget/lottie/native/lottiestate.dart, lib/widget/lottie/web/lottiestate.dart
Things done in this PR:
- Refactored some code
- Added support for forward(), reverse(), reset() and stop() methods to the Lottie widget.
- Added onForward, onReverse, onComplete, onStop callbacks to the Lottie widget.
- Added autoPlay parameter.
=> LOTTIE - Refactored code, added support for methods and callbacks

lib/widget/Text.dart
Reverts EnsembleUI/ensemble#969
=> Revert "enhance/selectable-text"

lib/framework/notification_manager.dart, lib/layout/data_grid.dart, lib/util/utils.dart, test/utils_test.dart
Ticket: [#688](https://github.com/EnsembleUI/ensemble/issues/688)
=> Add nested sort functionality for DataGrid

lib/framework/scope.dart, lib/screen_controller.dart
context https://discord.com/channels/1031982848485359626/1174309353357058119
=> fix: location scope issue

lib/framework/scope.dart, lib/screen_controller.dart
- reverted the old code
- simply set lat/lng on the current scopeManager.
=> properly fixed location's lat/lng

lib/framework/view/has_selectable_text.dart, lib/layout/data_grid.dart, lib/screen_controller.dart, lib/widget/Text.dart, lib/widget/lottie/native/lottiestate.dart, lib/widget/lottie/web/lottiestate.dart
Relates to: #914. Forgot to add a dispose for the animation controller which was causing warnings to occur. So added it.
=> Disposed animation controller for lottie

.github/workflows/pr.yml
Fixed the version of flutter at 3.10.6 to run tests
=> Changed version to fix the test bug

lib/framework/data_context.dart, lib/widget/calendar.dart
closes: [#977](https://github.com/EnsembleUI/ensemble/issues/977)
=> Custom Header

lib/framework/studio_debugger.dart, lib/framework/widget/widget.dart, lib/layout/box/box_layout.dart, lib/layout/stack.dart, lib/widget/Text.dart
Added the ability to show error in text widget for when the studio hangs.
#962
=> Changes StudioDebugger

assets/schema/ensemble_schema.json, lib/widget/calendar.dart
closes: [#974](https://github.com/EnsembleUI/ensemble/issues/974)
Sample EDL:
```yaml
Calendar:
id: calendar
rowHeight: 120
header:
Text: 
text: ${ensemble.formatter.customDate(calendar.focusDate, 'yMMM')}
tootlip:
date: ${(calendar.focusDate}
text: Hello world
backgroundColor: yellow
textStyle:
color: black
```
=> Added tooltip to calendar

assets/schema/ensemble_schema.json, lib/framework/view/page.dart, lib/page_model.dart
=> Made fixed content for footer

lib/widget/qr_code.dart, lib/widget/video.dart
closes https://github.com/EnsembleUI/ensemble/issues/1024
=> Changed deprecated APIs for QR code and Video

assets/schema/ensemble_schema.json, lib/widget/input/form_textfield.dart
Added a style called `toolbarDone` for setting the TextInput with keyboard toolbar with done button
=> Update textinput's keyboard toolbar with toolbarDone style

assets/schema/ensemble_schema.json, lib/framework/view/page.dart, lib/widget/helpers/unfocus.dart
Ticket - #1017
```yaml
View:
header:
title: EnsembleApp
styles:
unfocus: true  // Defaults to False
```
=> Dismiss keyboard when tapping the non-interactive views

lib/layout/helpers/list_view_core.dart, lib/layout/list_view.dart, pubspec.yaml
ListView core replaced from packaged to custom slivers.
Introduced simple api for infinite scroll usecase like:
- hasReachedMax ( to stop calling onScrollEnd)
- showLoading setter ( to show / hide loader through EDL)
=> listview: rewrite the simple listview core

lib/ensemble_app.dart, lib/layout/tab_bar.dart
closes: https://github.com/EnsembleUI/ensemble/issues/844
=> Dispatch changes when tab changes

lib/framework/view/page_group.dart, lib/layout/box/box_layout.dart
Ticket: [#1060](https://github.com/EnsembleUI/ensemble/issues/1060)
**Sample EDL**:
```yaml
ViewGroup:
Sidebar:
items:
- label: Home
icon:
name: home
page: Page1
- label: Button
icon:
name: input
page: Page2
header:
Column:
mainAxisSize: max
styles:
backgroundColor: green
padding: 24 20
children:
- Text:
text: Header
footer:
Column:
mainAxisSize: min
styles:
backgroundColor: green
padding: 24 20
children:
- Button:
styles:
gap: 20
label: Footer
```
=> Fix sidebar header and footer not rendering with view group

lib/widget/toggle_button.dart
Ticket: [#1044](https://github.com/EnsembleUI/ensemble/issues/1044)
**EDL**
```yaml
ToggleButton:
value: Blue
styles:
expanded: true
spacing: 10
runSpacing: 10
color: black
selectedColor: white
backgroundColor: white
selectedBackgroundColor: green
items:
- Blue
- Green
onChange: |
//@code
onChangeDemo.text = 'You selected toggle button value: ' +this.value;
```
=> Add expanded functionality for toggle button items

assets/schema/ensemble_schema.json, lib/widget/video.dart
Ticket: #1049
1. isInitialized
2. isBuffering
3. isLooping
4. isPlaying
5. isEnded
1. enableLoop property
2. autoplay property
3. volume property (0 to 1.0)
4. playbackRate property (0 to 2.0)
5. showControls property
6. loadingWidget property
1. play method
2. pause method
3. stop method
4. mute method
5. unmute method
6. seekTo method
1. onStart callback
2. onEnd callback
3. onChange callback (with position, milliseconds)
1. Added backward and forward with 10 seconds in the default controls
Sample EDL:
```yaml
View:
header:
title: Video
styles:
body:
Column:
styles: { gap: 16, padding: 24, crossAxis: center }
children:
- Text:
id: onChangeId
text: onChange
- Video:
id: videoId
source: https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 …
```
=> Improve video player controls and added new functionalities

lib/action/phone_contact_action.dart, lib/framework/action.dart, lib/framework/stub/contacts_manager.dart, lib/screen_controller.dart
**EDL:**
```yaml
View:
header:
title: PhoneContacts
styles:
scrollableView: false
body:
Column:
styles:
gap: 24
padding: 24
mainAxis: center
crossAxis: center
children:
- Button:
label: Get Phone Contacts
onTap:
getPhoneContacts:
onSuccess: |
//@code
console.log("Phone Number Fetched Successfully");
ensemble.storage.set('contacts', event.data['contacts']);
onError: |
//@code
console.log("Something went wrong!");
- ListView:
id: listView
styles: { expanded: true }
item-template:
data: ${ensemble.storage.contacts}
name: contact
template:
UserContact:
inputs:
contact: ${contact}
UserContact:
inputs:
- contact
styles: { gap: 10 }
onLoad:
getPhoneContactPhoto:
id: contactPhotoId
contactId: ${contact.id}
body:
Column:
styles: { gap: 2 }
children:
- Row:
children:
- Image:
source: …
```
=> Add a functionality for getting a photo from a contact

lib/framework/data_context.dart, lib/framework/view/page.dart
closes: https://github.com/EnsembleUI/ensemble/issues/1063
=> fix keyboard hides textfield

lib/widget/calendar.dart
- Setting each cell scope differently 
N.A
N.A
=> calendar cell scope updated

lib/ensemble.dart, lib/ensemble_provider.dart, lib/framework/data_context.dart, lib/framework/error_handling.dart, lib/framework/scope.dart, lib/framework/view/page.dart, lib/framework/widget/custom_view.dart, lib/framework/widget/screen.dart, lib/framework/widget/view_util.dart, lib/page_model.dart
see detailed description in https://github.com/EnsembleUI/ensemble/issues/62
=> Reusable code libs 62

lib/widget/calendar.dart
- New method clearRange and remove auto range clearing from un select
=> calendar: new method clearRange

lib/widget/input/form_helper.dart
In this PR, you can able to add color to the checkbox leading and trailing text color.
```yaml
Checkbox:
trailingText: I am a checkbox
styles:
fontSize: 30
labelStyle:
color: green
fontWeight: bold
```
=> Add color to form field text style for checkbox leading and trailing text

lib/util/utils.dart, lib/widget/carousel.dart
Ticket: #1173
Docs: https://github.com/EnsembleUI/ensemble_docs/pull/138
Schema: https://github.com/EnsembleUI/ensemble-web-studio/pull/711
Added a few style properties
1. aspectRatio
2. autoPlayAnimationDuration
3. autoPlayCurve
4. enlargeCenterPage
5. enlargeFactor
6. direction
7. cacheKey
8. buildOnDemand
9. buildOnDemandLength
=> Added few more properties to carousel widget

lib/action/action_invokable.dart
Invoke the getPhoneContactPhoto from JS code
```yaml
UserContact:
inputs:
- contact
styles: { gap: 10 }
onLoad: |
//@code
ensemble.getPhoneContactPhoto({
id: "contactPhotoId",
contactId: contact.id
});
```
=> Add getPhoneContactPhoto to action invokable

lib/framework/widget/toast.dart
Ticket: [#1108](https://github.com/EnsembleUI/ensemble/issues/1108)
Sample EDL:
**Large Text Example:**
```yaml
View:
header:
title: Toast
styles:
body:
Column:
styles:
gap: 30
children:
- Row:
styles: { gap: 6, mainAxis: center }
children:
- TopLeft
- Top
- TopRight
- Row:
styles: { gap: 6, mainAxis: center }
children:
- CenterLeft
- Center
- CenterRight
- Row:
styles: { gap: 6, mainAxis: center }
children:
- BottomLeft
- Bottom
- BottomRight
TopLeft:
body:
Button:
label: TopLeft
onTap:
showToast:
message: Success! by default at screen's top right. Success! by default at screen's top right.
options:
dismissable: true
type: success
alignment: topLeft
duration: 3
styles:
backgroundColor: 0xFFEDEDED
padding: 16 24
Top:
body:
Button:
label: Top
onTap:
showToast:
message: …
```
=> Fix toast message text wrap issue

lib/widget/calendar.dart
closes: https://github.com/EnsembleUI/ensemble/issues/1207
=> Calendar: control outside date visibility

lib/widget/input/dropdown.dart
closes: https://github.com/EnsembleUI/ensemble/issues/1183
EDL:
```yaml
Dropdown:
label: Colors
floatLabel: true
autoComplete: true
createNewItem:
label: Create "${newValue}"
icon: add
onTap: |
ensemble.debug(newValue);
items:
- Red
- Blue
- Green
```
=> Dropdown enhance

lib/widget/calendar.dart
closes: https://github.com/EnsembleUI/ensemble/issues/1208
EDL: 
```yaml
Calendar:
rowSpans:
spanPerRow: 3
topMargin: 18
span-template:
data: ${ensemble.storage.rowSpan}
name: span
span:
rowId: ${span.rowId} # depending spanPerRow here id can be 1 | 2 | 3
start: ${span.start}
end: ${span.end}
widget:
CustomSpan:
inputs:
span: ${span}
```
=> rowId add to span template

lib/framework/action.dart, lib/framework/data_context.dart
https://github.com/EnsembleUI/ensemble/issues/1229
=> https://github.com/EnsembleUI/ensemble/issues/1229 support for conditional actions and action groups

lib/action/invoke_api_action.dart, lib/framework/config.dart, lib/framework/data_context.dart, lib/util/http_utils.dart
=> https://github.com/EnsembleUI/ensemble/issues/451 mockresponse framework

lib/ensemble_app.dart, lib/framework/scope.dart, lib/framework/theme_manager.dart, lib/framework/widget/screen.dart, lib/framework/widget/view_util.dart, lib/layout/templated.dart, lib/page_model.dart
#1264 
[doc](https://docs.google.com/document/d/1CX7c4TNYGCzMbgSl6gviWcJT_wXL9jn3Mf477pNZXPg/edit#heading=h.m24iuq7flrhw)
=> Themes #1264

lib/ensemble_app.dart, lib/framework/ensemble_widget.dart, lib/framework/theme_manager.dart, lib/framework/widget/widget.dart, lib/layout/form.dart, lib/layout/tab_bar.dart, lib/page_model.dart, lib/widget/helpers/controllers.dart, lib/widget/widget_util.dart
Render the children eve if visiblity is false, such that we can still reference widgets underneath with their IDs
=> Render children even if visible is false

lib/framework/widget/view_util.dart, lib/page_model.dart
=> #1295 changed class to className to be consistent with react

lib/ensemble_app.dart, lib/framework/config.dart
=> https://github.com/EnsembleUI/ensemble/issues/1300 persistent themes

lib/action/Log_event_action.dart, lib/ensemble.dart, lib/ensemble_provider.dart, lib/framework/action.dart, lib/framework/data_context.dart, lib/framework/logging/console_log_provider.dart, lib/framework/logging/firebase_log_provider.dart, lib/framework/logging/log_manager.dart, lib/framework/logging/log_provider.dart, lib/provider.dart, pubspec.yaml
=> 1316 analytics

lib/widget/conditional.dart
closes: https://github.com/EnsembleUI/ensemble/issues/1328
=> Added widget node to conditional

lib/ensemble_app.dart
=> #1337 eventbus must not be closed in dispose as it is a singleton

pubspec.yaml
Closes: 
Brief description of what is fixed or changed
(If applicable)
=> https://github.com/EnsembleUI/ensemble/issues/1363

lib/framework/apiproviders/api_provider.dart
#1365 
Closes: 
Brief description of what is fixed or changed
(If applicable)
=> fixed the case when api providers is not available on the buildcontext

lib/widget/helpers/HasTextPlaceholder.dart, lib/widget/helpers/form_helper.dart, lib/widget/input/dropdown.dart, lib/widget/input/form_date.dart, lib/widget/input/form_textfield.dart, lib/widget/input/form_time.dart
Closes: 
Brief description of what is fixed or changed
(If applicable)
=> move from hintText/hintStyle to placeholder/placeholderStyle

lib/layout/tab/base_tab_bar.dart, lib/layout/tab/scrollable_tab_bar.dart, lib/layout/tab/tab_bar_controller.dart, lib/layout/tab_bar.dart, lib/widget/widget_registry.dart, pubspec.yaml
Closes: 
Brief description of what is fixed or changed
(If applicable)
=> Scrollable tabbar

lib/action/invoke_api_action.dart
=> fixes #1373 error response object being null in onError

lib/framework/menu.dart, lib/framework/studio/studio_debugger.dart, lib/page_model.dart
Closes https://github.com/EnsembleUI/ensemble/issues/1372
There was a bug that the assertion for the immediate parent to be stack if we have parameters like stack positions then it would freeze the entire studio as the flutter app would crash due to improper layout. So fixed those assertions
=> Added fix for the assertion for stack widget

modules/ensemble/lib/framework/apiproviders/http_api_provider.dart
SSL pinning is not for Web, so studio won't work
=> fix: SSL pinning

modules/bracket/pubspec.yaml, modules/ensemble/lib/action/get_network_info_action.dart, modules/ensemble/lib/framework/action.dart, modules/ensemble/lib/framework/stub/network_info.dart, modules/ensemble_network_info/lib/network_info.dart, modules/ensemble_network_info/pubspec.yaml, starter/lib/generated/ensemble_modules.dart, starter/pubspec.yaml
=> 1433 networkinfo

modules/ensemble/lib/util/utils.dart, modules/ensemble/lib/widget/confirmation_input.dart, modules/ensemble/lib/widget/input/form_textfield.dart
Closes https://github.com/EnsembleUI/ensemble/issues/1495
Added the autofillHints attribute for the TextInput and also added autofillEnabled for the OTP field
=> Added autofillHints attribute for text fields

modules/ensemble/lib/framework/bindings.dart, modules/ensemble/lib/framework/data_context.dart, modules/ensemble/lib/framework/data_utils.dart, modules/ensemble/lib/framework/scope.dart, modules/ensemble/lib/layout/templated.dart, modules/ensemble/lib/util/utils.dart, modules/ensemble/lib/widget/loading_container.dart
=> Disable recursiveEval() until we have a less error-prone mechanism than passthroughSetters()

modules/ensemble/lib/widget/conditional.dart
ticket: https://github.com/EnsembleUI/ensemble/issues/1544
=> Added conditions as passthrough

modules/ensemble/lib/action/bottom_sheet_actions.dart, modules/ensemble/lib/action/get_network_info_action.dart, modules/ensemble/lib/ensemble.dart, modules/ensemble/lib/framework/apiproviders/firestore/firestore_app.dart, modules/ensemble/lib/framework/apiproviders/firestore/firestore_types.dart, modules/ensemble/lib/framework/data_context.dart, modules/ensemble/lib/framework/data_utils.dart, modules/ensemble/lib/framework/menu.dart, modules/ensemble/lib/framework/stub/network_info.dart, modules/ensemble/lib/framework/theme_manager.dart, modules/ensemble/lib/framework/widget/view_util.dart, modules/ensemble/lib/page_model.dart, modules/ensemble/lib/util/utils.dart, modules/ensemble/lib/widget/confirmation_input.dart, modules/ensemble/lib/widget/text.dart, modules/ensemble/lib/widget/text/expandable_text.dart, modules/ensemble/lib/widget/webview/webview.dart, modules/ensemble/lib/widget/widget_registry.dart, modules/ensemble_network_info/lib/network_info.dart, modules/ensemble_ts_interpreter/lib/invokables/invokablecommons.dart, modules/ensemble_ts_interpreter/lib/parser/newjs_interpreter.dart, modules/ensemble_ts_interpreter/test/new_interpreter_tests.dart, modules/otp_pin_field/lib/src/otp_pin_field_state.dart
Problem here is the body widget is being recreated inside the Builder, which can be triggered 5+ times. Normally Flutter knows how to re-use the widget but we don't have any unique identifier for it to compared to. The fix is simply to move the body widget creation outside and re-use it inside the Builder
=> Fixed Bottom Modal recreating its content multiple times when keyboard appears/disappears

modules/ensemble/lib/widget/youtube/youtube.dart
Closes https://github.com/EnsembleUI/ensemble/issues/1522
=> Fixes youtube player keeps on playing in background

modules/ensemble/lib/widget/input/form_time.dart
It was created while resolving the conflict.
=> small fix of bracket in Time widget

modules/camera/lib/camera.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1658
=> fix:camera model dismiss

modules/ensemble/lib/action/upload_files_action.dart, modules/ensemble/lib/framework/data_context.dart, modules/ensemble/lib/util/upload_utils.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1663
=> file upload handles map and multiple fieldName

modules/ensemble/lib/widget/signature.dart, modules/ensemble/lib/widget/widget_registry.dart, modules/ensemble/pubspec.yaml
ticket: https://github.com/EnsembleUI/ensemble/issues/1664
Example EDL of usecase defined in ticket:
```yaml
Column:
styles:
padding: 24
gap: 8
children:
- Signature:
styles: 
penColor: green
value: ${ensemble.storage.signature}
penStrokeWidth: 10
disabled: true
borderColor: red
borderWidth: 5
- Button:
label: Enter sign
onTap:
showBottomSheet:
body:
Column:
styles:
height: 500
padding: 20
children:
- Signature:
id: hello
styles: 
penColor: green
penStrokeWidth: 10
height: 300
disabled: false
strokeCap: round
borderColor: red
borderWidth: 5
borderRadius: 20
- Row:
styles:
mainAxis: spaceBetween
padding: 20 10
children:
- Button:
label: Clear
onTap: |
hello.clear();
- Button:
label: Save
onTap: |
ensemble.storage.signature = hello.value;
```
=> updated signature widget

modules/ensemble/integration_test/framework/test_helper.dart, modules/ensemble/lib/ensemble.dart, modules/ensemble/lib/framework/definition_providers/ensemble_provider.dart, modules/ensemble/lib/framework/definition_providers/host_cache_provider.dart, modules/ensemble/lib/framework/definition_providers/local_provider.dart, modules/ensemble/lib/framework/definition_providers/provider.dart, modules/ensemble/lib/framework/definition_providers/remote_provider.dart, modules/ensemble/lib/framework/definition_providers/validation_provider.dart
making sure the async initialization code is properly awaited upon, this will avoid timing issues.
=> https://github.com/EnsembleUI/ensemble/issues/1680

modules/ensemble/lib/widget/tooltip.dart, modules/ensemble/lib/widget/widget_registry.dart
ticket: https://github.com/EnsembleUI/ensemble/issues/1628
Example Video & EDL is added in ticket.
once PR gets approved, will create schema PR and update docs.
=> added ToolTip widget

modules/ensemble/lib/action/upload_files_action.dart, modules/ensemble/lib/util/upload_utils.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1686
=> camera blob default value, uploadFiles support multiple file

modules/ensemble/lib/widget/EnsembleAccordion.dart, modules/ensemble/lib/widget/widget_registry.dart
Change `collapsible` widget name with `accordion` and change `isAccordion` prop with `limitExpandedToOne`
Closes https://github.com/EnsembleUI/ensemble/issues/1688
=> updated collapsible to Accordion

modules/ensemble/lib/action/bluetooth_action.dart, modules/ensemble/lib/framework/action.dart, modules/ensemble/lib/framework/stub/bluetooth.dart, modules/ensemble/lib/framework/widget/screen.dart, modules/ensemble_bluetooth/CHANGELOG.md, modules/ensemble_bluetooth/LICENSE, modules/ensemble_bluetooth/README.md, modules/ensemble_bluetooth/lib/ensemble_bluetooth.dart, modules/ensemble_bluetooth/pubspec.yaml, modules/ensemble_bluetooth/test/ensemble_bluetooth_test.dart, starter/lib/generated/ensemble_modules.dart, starter/pubspec.yaml
issue: https://github.com/EnsembleUI/ensemble/issues/1637
=> Bluetooth module: Support for BLE devices

modules/ensemble/lib/widget/accordion.dart, modules/ensemble/lib/widget/widget_registry.dart
New Example EDL for items
```yaml
View:
styles:
header:
title: "Collapsible Widget"
body:
Column:
styles:
padding: 24
gap: 8
children:
- Button:
label: hello
onTap: |
console.log( hello.openSection(1) );
- Accordion:
id: hello
styles:
limitExpandedToOne: false
headerStyle:
width: 50
backgroundColor: red          
borderColor: green            
borderColorOpened: red        
backgroundColorOpened: grey   
borderWidth: 5                
borderRadius: 5              
bodyStyle:
backgroundColor: white        
borderColor: green          
borderWidth: 3               
horizontalPadding: 20    
flipRightIconIfOpen: true
openAndCloseAnimation: false
paddingBetweenOpenSections: 10
paddingBetweenClosedSections: 10
items:
- header:
Text:
text: "Section 1 Heading"
body:
Text: …
```
=> updated `accordion` controller and props

modules/ensemble/lib/widget/visualization/chart_js.dart, modules/js_widget/lib/src/mobile/js_widget.dart, modules/js_widget/lib/src/web/js_widget.dart
This reverts commit 29684b97e604a63a3e124d409b0c2f730ae943fa, reversing changes made to 102ab7c3bb9277b7cb73b1bb364a493094b1be9a.
=> Revert "Merge pull request #1690 from EnsembleUI/chartJS0x45"

modules/ensemble/lib/widget/slidable.dart
ticket Link: https://github.com/EnsembleUI/ensemble/issues/1705
Example code and working video is in Ticket.
=> updated swipe-to-dismiss functionality in slidable

modules/ensemble/lib/layout/tab/base_tab_bar.dart, modules/ensemble/lib/layout/tab/scrollable_tab_bar.dart, modules/ensemble/lib/layout/tab_bar.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/1707
Example EDL in ticket.
=> [1707] added visible porperty in scrollable tabbar

starter/ios/Podfile
https://github.com/EnsembleUI/ensemble/issues/1729
=> update FirebaseFirestore for iOS

modules/chat/lib/ensemble_chat.dart
ticket: https://github.com/EnsembleUI/ensemble/issues/1758
Also `onMessageSend` was being executed after `onMessageReceived` 😂 so that's why rearranged its structure to execute `onMessageSend` and then we process the llm request and execute `onMessageReceived` after that.
Example EDL is added in ticket
=> [1758] added `onMessageReceived` Action for chat widget

modules/ensemble/lib/action/Log_event_action.dart, modules/ensemble/lib/framework/stub/moengage_manager.dart, modules/ensemble/lib/util/moengage_utils.dart, modules/ensemble/pubspec.yaml, modules/moengage/lib/moengage.dart
was getting error while creating a build where even moengage was not enabled bcz we were using moengage package in ensemble module to get access to some Enums from it, so removed that package.
=> removed moengage dependency from ensemble module

CHANGELOG.md, modules/auth/pubspec.yaml, modules/bracket/pubspec.yaml, modules/camera/pubspec.yaml, modules/chat/pubspec.yaml, modules/connect/pubspec.yaml, modules/contacts/pubspec.yaml, modules/deeplink/pubspec.yaml, modules/ensemble/CHANGELOG.md, modules/ensemble/pubspec.yaml, modules/ensemble_bluetooth/pubspec.yaml, modules/ensemble_network_info/pubspec.yaml, modules/file_manager/pubspec.yaml, modules/firebase_analytics/pubspec.yaml, modules/location/pubspec.yaml, modules/moengage/pubspec.yaml, starter/pubspec.yaml
=> chore(release): publish packages

modules/ensemble_bluetooth/pubspec.yaml
Ticket: https://github.com/EnsembleUI/ensemble/issues/1826
=> bluetooth: remove camera reference

starter/scripts/modules/enable_bluetooth.dart, starter/scripts/modules/enable_camera.dart, starter/src/modules_scripts.ts
fix BLE Android permission
fix camera permission to include photo library description as well for ios
=> fix: update Bluetooth permissions for Android

modules/ensemble/lib/action/saveFile/save_file.dart, modules/ensemble/lib/action/saveFile/save_mobile.dart, modules/ensemble/lib/framework/stub/file_manager.dart, modules/ensemble/pubspec.yaml, modules/file_manager/lib/file_manager.dart, modules/file_manager/pubspec.yaml
fixes: https://github.com/EnsembleUI/ensemble/issues/1928
=> Refactor file saving logic to use FileManager for image saving

modules/camera/lib/camera_manager.dart, modules/camera/lib/face_detection_camera.dart, modules/camera/lib/web/face_detection_stub.dart, modules/camera/lib/web/face_detection_web.dart, modules/camera/lib/web/smart_face_camera_web.dart, modules/camera/web/face_detection.js
REF: https://discord.com/channels/1031982848485359626/1348639282163613737/1353597998751289376
EDL:
```yaml
- Button:
label: Open Camera
onTap:
openCamera:
id: cameraWithFaceDetection
options:
initialCamera: front
faceDetection:
enabled: true
autoCapture: false
performanceMode: accurate
accuracyConfig: # accuracyConfig is only supported on web
detectionThreshold: 0.5
intersectionRatioThreshold: 0.9
extraHeightFactor: 0.6
inputSize: 224
landmarkRatio: 0.95
frameMargin: 0.05
tiltAngleThreshold: 6
horizontalCenterTolerance: 0.08
earThreshold: 0.25
minFaceWidthRatio: 0.18
maxFaceWidthRatio: 0.82
qualityPassThreshold: 0.8
yawLowerThreshold: 0.85
yawUpperThreshold: 1.15
message: "Align your face in the square"
messageStyle:
color: "#FF0000"
fontSize: 20
onCapture:
uploadFiles:
id: uploader …
```
=> fix face detection image capture

modules/ensemble/lib/action/action_invokable.dart
Github Ticket: https://github.com/EnsembleUI/ensemble/issues/1943
eventLog can now be used from JS.
It is exposed just like `showDialog` or `showToast`
EDL:
```yaml
- Button:
label: Log Event using JS Code
onTap:
executeCode:
body: |
//@code
ensemble.logEvent({
"name": "event from code", 
"provider": "firebase", 
"parameters": {"timestamp": ensemble.formatter.now().getDateTime()}});
```
=> logEvent from JS

modules/ensemble/lib/widget/input/taginput/taginput.dart
So TagInput was working fine, but due to `ensemble.storage`, the whole widget tree gets rebuild, and when `TagInput` was being rebuilt, the controller was losing its value which was the result I'm null errors.
=> [BUG] Fixed the error getting tags being null after a rebuild

modules/camera/web/image_worker.js
Reverts EnsembleUI/ensemble#1951
Reverting this as its causing infinite loop errors in console
=> Revert "Image Worker"

modules/ensemble/lib/widget/input/taginput/taginput.dart, modules/ensemble/pubspec.yaml
Ticket: https://github.com/EnsembleUI/ensemble/issues/1955
**Fixed:**
- Once we dispose tagInput, and try to use it again, it was giving an error. Fixed it.
- Multiple `tagInput` in a screen was causing issues. Fixed it.
- If `Triggers` are not defined, then it was giving an initialization error as it was being declared late. Fixed it.
- `Trigger` styles were not being applied correctly. Fixed it.
- Triggers now have a new property `triggerType` which can be mapped to the property we will also define in the data to figure out which data to display upon which trigger.
- Also exposed a getter to get the current used trigger character using its id `tagInputId.currentTriggerChar`
- Added `initialTag` property to let the developer add a tag to the tagInput at the beginning or at runtime using …
=> [BUG] fixing Late initialization errors in tagInput

modules/camera/lib/qr_code_scanner.dart, modules/camera/pubspec.yaml
Before we were using `qr_code_scanner` package but it isn't being maintained properly anymore stated by there owners and is causing errors `namespace not specified`.
So using a new package created by the same owners `mobile_scanner` and reafactored the implementation.
Here is the `ensemble_live` debug apk created using this camera branch, please check out, QR_code is working as expected: https://drive.google.com/file/d/1K-TfDxN6WNzjL7dqFyj83YXLBoVe5kPE/view?usp=sharing
=> [Update] Changed QR_Code package

modules/ensemble/lib/framework/view/page.dart
Fixes: https://github.com/EnsembleUI/ensemble/issues/1982
Added `didUpdateWidget` to sustain `scrollController` state:
https://github.com/user-attachments/assets/b85c0d2a-4476-47d4-bfde-c668520e408d
=> Fix Animation stuck

README.md, modules/ensemble/lib/framework/encrypted_storage_manager.dart
- Updated readme for releasing new version
- Removed print statements that was left in one of the PR for secure storage.
=> Readme update

modules/ensemble/lib/framework/apiproviders/http_api_provider.dart, modules/firebase_analytics/lib/firebase_analytics.dart
This PR contains 2 changes:
1. `sslConfig` property in API.
We already had environment variables to control the ssl behavior of APIs, but those are global, once defined, they will be applied to all API, but we need some APIs to behave different based on some conditions, for that we need to add these properties in API defination, to override the variables behaviors.
- ENV variables would still work, and be applied to all API calls.
- APIs with these properties will have different behavior as they will get overriden.
Example EDL:
```yaml
getUserData:
url: https://api.example.com/users
method: GET
sslConfig:
pinningEnabled: true | false
bypassPinning: true | false
bypassPinningWithFingerprint: true | false
fingerprintKey: "api_example_com_fingerprint" # key of secureStorage
headers: …
```
=> Added sslConfig in APIs and updated firebase analytics

modules/ensemble/lib/action/key_chain_actions.dart
Evaluated values of keyChainFunctions
=> Evaluated values of keyChainFunctions

starter/scripts/modules/enable_adobe_analytics.dart, starter/src/modules_scripts.ts
- Added a new script to enable Adobe Analytics with necessary configurations.
- Updated the modules_scripts.ts to include the Adobe Analytics module and its parameters.
- Enhanced pubspec.yaml to reference the Adobe Analytics library with dynamic versioning.
=> feat: implement Adobe Analytics module integration for Build System

modules/ensemble_ts_interpreter/lib/invokables/invokablecontroller.dart
- Enhanced the sorting method to handle floating point comparisons by converting them to integers.
- Updated the 'slice' method to allow for creating a shallow copy of the entire list when no arguments are provided.
=> fix(invokable): improve list sorting and slicing functionality

modules/ensemble/lib/widget/input/slider/slider.dart, modules/ensemble/lib/widget/input/slider/slider_controller.dart, modules/ensemble/lib/widget/input/slider/slider_state.dart
Added new properties `onChangeStart` and `onChangeEnd`.
=> Added new properties to slider.

starter/scripts/modules/enable_auth.dart
https://github.com/user-attachments/assets/d768b313-db59-40f2-a58c-c4985d1b779c
=> feat(auth): add support for Apple Sign In by updating iOS entitlements

modules/ensemble/lib/action/saveFile/save_file.dart
issue: https://github.com/EnsembleUI/ensemble/issues/2073
=> fix: evaluating the saveFile action properties

.github/workflows/build.yml, modules/ensemble/lib/framework/view/page.dart, modules/ensemble/lib/page_model.dart
- Implemented collapsible header functionality with visibility control based on storage changes.
- Added listeners for titleBarHeight and collapsibleHeader visibility to enable reactive updates.
- Enhanced AppBar behavior to adjust height based on collapsible header state.
=> feat(page): add collapsible header support and dynamic title bar height updates

modules/ensemble/lib/screen_controller.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/2089
=> Fix: `ensemble.storage.*` propagation to page groups as well.

modules/ensemble/lib/framework/apiproviders/firestore/firestore_app.dart
Ticket: https://github.com/EnsembleUI/ensemble/issues/2092
=> fix: converted Date objects to Timestamps
